### PR TITLE
Moonbeam/Moonriver  update logos and colors

### PR DESCRIPTION
**Pull request by albertov19**
### ✅ Checklist

- [x] `npx changeset` was attached.
- [x] **Covered by automatic tests.** 
- [x] **Impact of the changes:** 

### 📝 Description

Updated the Moonbeam/Moonriver logos and colors to follow the new [Moonbeam/Moonriver brand guidelines](https://guidelines.moonbeam.foundation)

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Review by ypolishchuk-ledger — APPROVED** [review]

**Comment by albertov19** [comment]
Hey @ypolishchuk-ledger any updates here 😄  thanks in advance

**Comment by albertov19** [comment]
Waiting on review from the Ledger Team :)

**Review by bharamboure-ledger — DISMISSED** [review]

**Comment by albertov19** [comment]
Hey all - any updates here? Thanks in advance

**Review by VicAlbr — DISMISSED** [review]

**Comment by albertov19** [comment]
@Wozacosta I pushed new SVGs following your suggestions, thanks!

@VicAlbr @bharamboure-ledger please check again 🙏

**Comment by Wozacosta** [comment]
Checked again, didn't display correctly, here's the versions I modified that make them displayable in desktop: 

MOVR
GLMR

**Comment by albertov19** [comment]
Ah @Wozacosta but then the checker is not correct. Your SVGS have just a `viewBox` and an `image` tag that has the `base64` content while the ones I've been working with have the geometric definitions with `circle` and `path`, etc. Nevertheless, your image does not pass the provided SVG checker tool.

Unsure how to proceed as the latest images I tested pass the checker.

**Comment by albertov19** [comment]
@Wozacosta Hey, I hope you are well. Any thoughts on my post above? Would love to get this merged

**Comment by Wozacosta** [comment]
Hey @albertov19, the SVG checker tool is mainly used for a quick overview of potential errors, but it not passing doesn't necessarily means the SVG won't be displayed. 
Have you tried exporting your svgs as plain svgs (or even plain pngs) ? 

I'll try to fit in some time to tests those then, but it would help if you're able to test how they're displayed in Ledger Live.

**Comment by albertov19** [comment]
Hey @Wozacosta  - I've pushed another commit that should solve all issues! The problem I was having was that I was uploading a `<circle>` that enclosed the icon, so Ledger was recoloring the entire symbol circle. 

The last SVGs are OK in Ledger's SVG checker, but I also built Ledger Live locally with these SVGs, and they show fine 😄 

It was definitely a learning experience haha, hope this helps getting this PR merged 🚀 

image
image

**Comment by Wozacosta** [comment]
Amazing work, Im testing it on mobile and if that's good I'll approve!

**Comment by Wozacosta** [comment]
Mobile looks good: 


screencap-2024-10-07T152354 608Z
screencap-2024-10-07T152334 671Z

**Review by Wozacosta — APPROVED** [review]

**Comment by Wozacosta** [comment]
Don't forget to rebase your PR, somes failing tests will be successful then.

**Comment by albertov19** [comment]
@Wozacosta, I noticed on mobile that there is a minimal margin. I don't have an easy way to test the mobile version, but I bumped a version with larger margins that looks better on the desktop.

That is why your approval was dismissed

**Pull request merged**
