### PR TITLE
Add PLC Ultima (plcu) support

### PR DESCRIPTION
**Pull request by plcudeveloper**
### Context

- Impacted projects: [live-desktop, @ledgerhq/live-common]
- Linked resource(s): **N/A**

### Checklist
- [ ]  Test coverage: Did you write any tests to cover the changes introduced by this pull request?
- [x]  Atomic delivery: Is this pull request standalone? In order words, does it depend on nothing else?
- [x]  No breaking changes: Does this pull request contain breaking changes of any kind? If so, please explain why.

### Demo
**N/A**

### Expectations to reach
Please make sure you follow these [Important Steps](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps).

Pull Requests must pass the CI and be internally validated in order to be merged.

### CODE REVIEW

**Comment by elbywan** [comment]
@plcudeveloper  Can you please fill in the PR template? Otherwise this PR will get closed. Thanks 🙇.

**Comment by plcudeveloper** [comment]
> @plcudeveloper Can you please fill in the PR template? Otherwise this PR will get closed. Thanks bow.

Done.
Thank you, Julien !

**Comment by plcudeveloper** [comment]
@elbywan 
hi Julien,
the PR is assigned on me, should it be be re-assigned to someone from Ledger to proceed?
Thanks!

**Comment by elbywan** [comment]
Hey @plcudeveloper,

> the PR is assigned on me, should it be be re-assigned to someone from Ledger to proceed?

No need, our blockchain team will review the PR when possible 😉.

**Comment by plcudeveloper** [comment]
hi @haammar-ledger , could you please review the PR?
thank you!

**Comment by plcudeveloper** [comment]
Hello @haammar-ledger ,
Could you please review the PR or tell whom I can ask for that?
Thanks you!

**Comment by haammar-ledger** [comment]
Hi @plcudeveloper thank you for your contribution, but it appears the Nano application is still under review.
Closing this for now, we will contact you to reopen it once the application is reviewed.

**Pull request closed without merging**
