### PR TITLE
fix: LIVE-5026 remove stake from polygon and binance accounts

### PR DESCRIPTION
**Pull request by sarneijim**
### 📝 Description

LLD - Remove ETH staking banner on BNB and Polygon Page

### ❓ Context

- **Impacted projects**: 
- LLD
- **Linked resource(s)**: 
- https://ledgerhq.atlassian.net/browse/LIVE-5026

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by hedi-edelbloute — APPROVED** [review]
LGTM but check for safety the impact on other ethereum related chains, search `family: "ethereum"` in `libs/ledgerjs/packages/cryptoassets/src/currencies.ts`, should be ok tho

**Comment by sarneijim** [comment]
> LGTM but check for safety the impact on other ethereum related chains, search `family: "ethereum"` in `libs/ledgerjs/packages/cryptoassets/src/currencies.ts`, should be ok tho

Yes, the idea is remove "stake" from any currency that it is not pure ethereum.

**Review by mcoursier-ledger — APPROVED** [review]
Lgtm

**Review by ggilchrist-ledger — APPROVED** [review]
LGTM

**Pull request merged**
