### PR TITLE
LIVE-2498 Update LLC dependencies - @polkadot

### PR DESCRIPTION
**Pull request by haammar-ledger**
**Duplicating here as the PR template seems to have a glitch...**
Update some polkadot dependencies in LLC.

### 📝 Description

Update some polkadot dependencies in LLC.

**:warning: Can't update `@polkadot/wasm-crypto` because it breaks LLM when updated :warning:** 
Will need to be addressed separately, Jira ticket: https://ledgerhq.atlassian.net/browse/LIVE-2976

### ❓ Context

- **Impacted projects**: `ledger-live-common` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-2498 

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

N/A

### 🚀 Expectations to reach

- [x] **Add account / receive / send on LLD**
- [x] **Add account / receive / send on LLM Android**
- [x] **Add account / receive / send on LLM iOS**

### CODE REVIEW

**Comment by haammar-ledger** [comment]
Integration tests run started: https://github.com/LedgerHQ/ledger-live/actions/runs/2690104116

**Comment by valpinkman** [comment]
> ### 📝 Description
> Update some polkadot dependencies in LLC.
> 
> **⚠️ The `@polkadot/wasm-crypto` dependency breaks LLM when updated ⚠️** Will need to be addressed separately.
> 

I kind of disagree with this statement. In the context of monorepo, everything must be in think to be able to merge to develop, or we break develop and compat, here with LLM. It's better to address the issue in this PR (but I still see it as Draft so I guess it's not over)

**Comment by haammar-ledger** [comment]
@valpinkman just to clarify, this PR does _not_ update `@polkadot/wasm-crypto`.
Maybe my message is confusing :smile: what I meant is updating it should be done later separately.
Basically this PR doesn't break anything, the updated packages are compatible with current version of `@polkadot/wasm-crypto`, so we'll just have to figure out with how to update it separately in the future...

Is this acceptable?

**Comment by valpinkman** [comment]
> @valpinkman just to clarify, this PR does _not_ update `@polkadot/wasm-crypto`. Maybe my message is confusing 😄 what I meant is updating it should be done later separately. Basically this PR doesn't break anything, the updated packages are compatible with current version of `@polkadot/wasm-crypto`, so we'll just have to figure out with how to update it separately in the future...
> 
> Is this acceptable?

Ok definitely then it is acceptable. Yes the message was confusing, but we are good I guess then :)

**Review by hedi-edelbloute — APPROVED** [review]

**Comment by haammar-ledger** [comment]
:information_source: **This should be merged**, last CI failure is an unrelated known issue on LLD UI tests, currently affecting all PRs.

**Pull request merged**
