### PR TITLE
[BUGFIX][CI] update `submit-bot-report` node version to `node20`

### PR DESCRIPTION
**Pull request by chabroA**
### 📝 Description

update submit-bot-report node version to node20
Since this action does not use `isomorphic-unfetch` anymore, we get a `ReferenceError: fetch is not defined` error
when running this action

This PR https://github.com/LedgerHQ/ledger-live/pull/4539 removed `isomorphic-unfetch` and actions using `fetch` should now rely on native fetch, available through `node20`. But the `submit-bot-report` action, that uses `fetch`, was not updated to use `node20` (still used `node16`). Resulting in a `ReferenceError: fetch is not defined` error when running this action.

cf. this run for example https://github.com/LedgerHQ/ledger-live/actions/runs/6039199972/job/16387304068#step:6:6152

Question:
- Why don't we update all actions from `node16` to `node20`?  (out of the 12 actions having a `using: node*` step, only 4 of them use `node20`, the 8 remaining still use `node16`)
- Why din't we update all the versions used by the `uses: actions/setup-node@v3` step, from `18` to `20`, as well?
https://github.com/LedgerHQ/ledger-live/blob/bfd4fef405f832489cc5258330e6483260c896d2/tools/actions/composites/bot/action.yml#L49-L53

### ❓ Context

- **Impacted projects**: `` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Comment by valpinkman** [comment]
Yo @chabroA, nice catch, sorry i missed it.

**Review by valpinkman — APPROVED** [review]

**Comment by valpinkman** [comment]
> Question: Why don't we update all actions from node16 to node20? (out of the 12 actions having a using: node* step, only 4 of them use node20, the 8 remaining still use node16)
Why din't we update all the versions used by the uses: actions/setup-node@v3 step, from 18 to 20, as well?

- We could bump all of them to be honest, I just wanted to make sure node20 engine would run the actions correctly before
- We didn't change the setup-node to 20 because we are still not using node 20 on the project (you can see the current node version in the .prototools files)

**Comment by chabroA** [comment]
Waiting for this run to complete successfully (confirm the issue is indeed fixed) before merging
https://github.com/LedgerHQ/ledger-live/actions/runs/6047102703

**Comment by chabroA** [comment]
This doesn't fix the issue https://github.com/LedgerHQ/ledger-live/actions/runs/6047102703

**Pull request closed without merging**
