### PR TITLE
- test scenario who checks if token account is displayed in Eth account

### PR DESCRIPTION
**Pull request by mdeidda-ledger**
### 📝 Description

This pr add a UI test scenario who allow to check if a token account is displayed in ETH account.

### ❓ Context

- No impact

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by mcoursier-ledger — APPROVED** [review]
LGTM :)

**Review by hedi-edelbloute — APPROVED** [review]

**Review by abdurrahman-ledger — APPROVED** [review]

**Pull request closed without merging**
