### PR TITLE
Support/dev portal links

### PR DESCRIPTION
**Pull request by cfranceschi-ledger**
### 📝 Description

I did this modification yesterday, but I needed to move the paragraph elsewhere so it's not deleted when the doc is generated again.

### ❓ Context

- **Impacted projects**: ``Third-party devs using this documentation

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

No demo

### CODE REVIEW

**Review by hedi-edelbloute — APPROVED** [review]

**Comment by gre** [comment]
> :x: @github-actions
[Test] Libraries / Test Docs (pull_request) Failing after 1m — Test Docs

somehow it still fails :'(

**Comment by gre** [comment]
https://github.com/LedgerHQ/ledger-live/runs/7741236346?check_suite_focus=true

**Comment by cfranceschi-ledger** [comment]
Ah too bad, well I will remove this part from the auto-generated doc and only update the other READMEs.

**Comment by gre** [comment]
It's just because there are two extra space at the end I think.

I think the command you can run locally is:

```
pnpm turbo run doc 
```

over your current PR and it will fix them all

**Review by hedi-edelbloute — APPROVED** [review]

**Review by gre — APPROVED** [review]

**Pull request merged**
