### PR TITLE
bugfix/LIVE 11372 swap moonpay transaction broadcasted screen is not seen

### PR DESCRIPTION
**Pull request by cng-ledger**
### 📝 Description

Platform exchange flow is missing transaction success content, supporting success flow with this PR

Code is mostly ported from Swap exchange drawer, including the page analytics

https://github.com/LedgerHQ/ledger-live/assets/138497251/5373c22e-1326-4e80-b99e-af24b32dabb9

### ❓ Context

- **JIRA or GitHub link**: [LIVE-11372](https://ledgerhq.atlassian.net/browse/LIVE-11372)

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

[LIVE-11372]: https://ledgerhq.atlassian.net/browse/LIVE-11372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by sarneijim — CHANGES_REQUESTED** [review]
Up to the team, but in my perspective, the responsibility of 'completeExchange' is solely to execute the transaction and nothing more. Following the transaction successful response from LL,  the provider has the flexibility to decide whether to display their own success message or utilise our custom swap methods.
Specific methods for these scenarios have been defined in the demo 0 at `apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx`.
If the rest of the team prefer to proceed with this approach, we need to remove those methods and update demo 0.

Faster speed on the provider implementation vs personalise dappexperience

**Comment by kallen-ledger** [comment]
@sarneijim I tend to agree with your point of view on this. However may be best to get products view on this tomorrow?

**Comment by lpaquet-ledger** [comment]
> Specific methods for these scenarios have been defined in the demo 0 at `apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx`. If the rest of the team prefer to proceed with this approach, we need to remove those methods and update demo 0.

So instead of all having them in the same place they would be scattered in the files where we need them ?

**Comment by cng-ledger** [comment]
@sarneijim @kallen-ledger 

Thanks for the comment. Here is my digestion of this, let me know if this is correct. 

We will implement:
- Separate Transaction success drawer / modal
- A new handler to display successful swap message. using the new drawer / modal

Then it will depend on the Provider to call this method to show success drawer, it the future any other providers can just call this new handler?

**Comment by sarneijim** [comment]
> @sarneijim @kallen-ledger
> 
> Thanks for the comment. Here is my digestion of this, let me know if this is correct.
> 
> We will implement:
> 
> * Separate Transaction success drawer / modal
> * A new handler to display successful swap message. using the new drawer / modal
> 
> Then it will depend on the Provider to call this method to show success drawer, it the future any other providers can just call this new handler?

Yes, I assume when you talk about drawer / modal is always drawer for lld. Is that correct?
We do not need a new "drawer" is the same one but defined from a different place.
And the providers can trigger them using custom methods
- Following my understood we have:
    - Save transaction and success message
    - Redirect to the history
Both are defined as a custom methods in: `apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx`
The only thing that we need to do is move them from this file (demo 0) to the main swap and add them as accesible methods in Moonpay manifest, then they can call them.

**Review by kallen-ledger — APPROVED** [review]

**Comment by cng-ledger** [comment]
Outcome is transaction success can stay within the platform exchange drawer for now. The saving swap to history logic should probably be centralised, however these will be a separate ticket

**Review by sarneijim — APPROVED** [review]

**Pull request merged**
