### PR TITLE
LIVE-1810 Update hw-app-eth dependencies - @ethersproject

### PR DESCRIPTION
**Pull request by haammar-ledger**
### 📝 Description

Upgrade @ethersproject/abi from 5.5.0 to 5.6.2
Upgrade @ethersproject/rlp 5.5.0 to 5.6.0

Maintenance update + confirm a transaction works on live-common with it.

### ❓ Context

- **Impacted projects**: @ledgerhq/live-common
  
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-1810

### ✅ Checklist

- [x] **Test coverage**: _Did you write any tests to cover the changes introduced by this pull request?_
- [x] **Atomic delivery**: _Is this pull request standalone? In order words, does it depend on nothing else?_
- [x] **No breaking changes**: _Does this pull request contain breaking changes of any kind? If so, please explain why._

### 🚀 Expectations to reach

- [x] **Add account / receive / send on LLD (linux)**
- [x] **Add account / receive / send on LLM (android)**
- [ ] **Add account / receive / send on LLM (iOS)**

### CODE REVIEW

**Review by alexalouit — APPROVED** [review]

**Review by valpinkman — APPROVED** [review]

**Review by gre — APPROVED** [review]

**Comment by gre** [comment]
please have a changeset that document exactly which library gets updated. we should try to stop these generic "dependencies update" title if possible 🙏 for clarity

**Review by gre — CHANGES_REQUESTED** [review]
^

**Comment by gre** [comment]
@haammar-ledger 
as Integration Tests isn't shipped yet, I would reco at least to run the bot against this PR.
As we can't trigger the bot on a given "ref" for now i think you can just add the branch name in one of the bot so it triggers on push 🤔

**Comment by haammar-ledger** [comment]
@gre thanks, I started this run https://github.com/LedgerHQ/ledger-live/actions/runs/2678521695

:crossed_fingers:

**Comment by haammar-ledger** [comment]
@gre The run fails with the unrelated issue of wrong `'hasFailed'` status...
Pending discussion about it with backend, does it mean we should HODL this PR?

**Comment by gre** [comment]
@haammar-ledger we should take in the snapshot update into develop. https://github.com/LedgerHQ/ledger-live/pull/675 
then everything will be supposed to pass. locally at least it passes.

**Review by hedi-edelbloute — APPROVED** [review]

**Comment by gre** [comment]
we can run again the integration tests

**Comment by haammar-ledger** [comment]
Integration tests run : https://github.com/LedgerHQ/ledger-live/actions/runs/2869812376

**Comment by haammar-ledger** [comment]
:information_source: Integration tests run: https://github.com/LedgerHQ/ledger-live/actions/runs/3047237986

**Comment by haammar-ledger** [comment]
ETH integrations tests still flaky and can't be trusted...

**Pull request closed without merging**
