### PR TITLE
[LLD] Dynamically set the minimum of global summary chart 

### PR DESCRIPTION
**Pull request by dkaplan65**
### ✅ Checklist

- [x] `npx changeset` was attached.
- [x] **Covered by automatic tests.** 
- [x] **Impact of the changes:** 
  - Sets the `suggestedMin` of the chart in the global summary to be the minimum of the `balanceHistory` that we are currently looking at

### 📝 Description

It is difficult to view the small changes in the balance if the values are much bigger than 0. Ideally, we are able to view the chart values in the relative range that we are currently viewing, making the viewing experience better.

Note that the mobile app already has this as the display - this PR is just to make it on parity with the desktop explorer as well.

This was originally opened with this PR: https://github.com/LedgerHQ/ledger-live/pull/6528, but it was closed to inactivity. 

@gre said he would talk to product about this but there was never an update.

## Old view:
Screenshot 2024-03-23 at 4 35 04 PM

## New view:
Screenshot 2024-03-23 at 4 34 44 PM

### ❓ Context

- **JIRA or GitHub link**: 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Review by gre — APPROVED** [review]

**Comment by gre** [comment]
sorry for missing the followup of this. Product agrees with the direction so we can proceed with this 👍  Thanks

**Comment by gre** [comment]
@dkaplan65 can you rebase with latest `develop` of our repository? the CI can't run it because of this. thanks

**Comment by dkaplan65** [comment]
> @dkaplan65 can you rebase with latest `develop` of our repository? the CI can't run it because of this. thanks

@gre - rebased - con someone from your team authorize the deployment?

Thank you!

**Review by gre — APPROVED** [review]

**Pull request merged**
