### PR TITLE
Remove firmware on ATOM spec

### PR DESCRIPTION
**Pull request by henrily-ledger**
### ❓ Context

Bot couldn't find the right elf for the specs tests in ATOM

- **Impacted projects**: [e.g. `live-desktop`, `@ledgerhq/live-common`]
@ledgerhq/live-common
- **Linked resource(s)**:

_Write a clear and concise description of what this pull request is about and why it is needed._

### ✅ Checklist

- [ ] **Test coverage**: _Did you write any tests to cover the changes introduced by this pull request?_
- [x] **Atomic delivery**: _Is this pull request standalone? In order words, does it depend on nothing else?_
- [x] **No breaking changes**: _Does this pull request contain breaking changes of any kind? If so, please explain why._

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by gre — APPROVED** [review]
as long as it pass CI. we can merge this as it only have an impact for live bot which will be the way to test if it works (at the moment it fail so hopefully it is going to not be worse 🤞 )

**Comment by valpinkman** [comment]
@henrily-ledger needs a changelog

don't forget to run `pnpm changelog` and define the type of update you've done

**Review by valpinkman — CHANGES_REQUESTED** [review]
Changelog needed

**Comment by haammar-ledger** [comment]
> Changelog needed

@valpinkman isn't this a purely technical change where a changeset isn't required? Only affects tests, zero impact on the user.

**Review by haammar-ledger — APPROVED** [review]

**Comment by valpinkman** [comment]
> > Changelog needed
> 
> @valpinkman isn't this a purely technical change where a changeset isn't required? Only affects tests, zero impact on the user.

My bad, I didn't see it was in a .spec file. Ok for me, I'll merge

**Review by valpinkman — APPROVED** [review]

**Pull request merged**
