### PR TITLE
test(lld): reinforce coverage of operations list of accounts & portfolio

### PR DESCRIPTION
**Pull request by gre**
### 📝 Description

following recent regression https://github.com/LedgerHQ/ledger-live/pull/3782 , this PR reinforces tests to screenshots the operations list.

i also notice that Portfolio page was screenshot AFTER the Add Account of EACH coin, which isnt needed, instead this introduces only ONE portfolio.spec.ts to cover that part and also includes a screenshot of the operations list.

### ❓ Context

- **Impacted projects**: `LLD` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by mcoursier-ledger — APPROVED** [review]
Many thanks

**Review by haammar-ledger — APPROVED** [review]

**Comment by gre** [comment]
let's wait the CI to fully pass, it was passing in the past, but i had to rebase develop and unfortunately i push forced away the screenshot diff. let's hope it pass again.

**Pull request merged**
