### PR TITLE
[QAA][Playwright] Fix playwright mocked test for features flags prod

### PR DESCRIPTION
**Pull request by abdurrahman-ledger**
### ✅ Checklist

- [ ] `npx changeset` was attached.
- [X] **Covered by automatic tests.** 
- [X] **Impact of the changes:** 
  - Playwright mocked tests

### 📝 Description

_We are going to update firebase testing environment to be the same as production. This PR aims at fixing the issues beforehand to prevent CI from being red too long._

### ❓ Context

- **JIRA or GitHub link**: 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Comment by abdurrahman-ledger** [comment]
update-screenshots

**Comment by abdurrahman-ledger** [comment]
\generate-screenshots

**Review by ypolishchuk-ledger — DISMISSED** [review]

**Review by Justkant — DISMISSED** [review]
LGTM on the files for wallet-api

**Review by bharamboure-ledger — APPROVED** [review]

**Review by ypolishchuk-ledger — APPROVED** [review]

**Review by Justkant — APPROVED** [review]

**Pull request merged**
