### PR TITLE
CN-604: Change Stake label to Yield for the UK, to Earn for the rest of the countries

### PR DESCRIPTION
**Pull request by adammino-ledger**
### ✅ Checklist

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [x] Impact of the changes: changing a label for staking for Bitcoin only

### 📝 Description

This PR changes the Label `Stake` to `Yield` for the UK, to `Earn` for the rest of the countries. The country detection is based on the Locale.

### ❓ Context

[JIRA-604](https://ledgerhq.atlassian.net/browse/CN-551)

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Review by KVNLS — DISMISSED** [review]

**Review by LucasWerey — APPROVED** [review]

**Review by Wozacosta — DISMISSED** [review]

**Comment by adammino-ledger** [comment]
There is a change on the requirement for this so it cannot be merged for now till that's clear.

**Review by abdurrahman-ledger — APPROVED** [review]

**Pull request merged**
