### PR TITLE
Add support for some ESDT tokens

### PR DESCRIPTION
**Pull request by AlexandruPislariu**
### 📝 Description

Add support for some ESDT tokens

### ❓ Context

- **Impacted projects**: `` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by haammar-ledger — COMMENTED** [review]
@AlexandruPislariu One test is failing: https://github.com/LedgerHQ/ledger-live/actions/runs/4323678223/jobs/7547558019#step:9:3001

It's based on the presence of `disableCountervalue` in the token data, I suggest you add this param to all ESDT tokens, in the same way it's done for other tokens.
You should also confirm their countervalue exists on coingecko at the same time, if it doesn't of course `disableCountervalue` should be `true`.

**Review by haammar-ledger — CHANGES_REQUESTED** [review]
Tests still failing, because of a small typo:
```diff
-disableCounterValue
+disableCountervalue
```

**Comment by aelmilligy-ledger** [comment]
Hi @AlexandruPislariu, 

Could you please have a look at the errors in the CI. You have typecheck and lint issues and also some docs to generate. Once done could you also do a rebase? 

Best regards.

**Review by haammar-ledger — COMMENTED** [review]
@AlexandruPislariu Could you make some progress on that PR?
As a reminder:
- One test snapshot to update (cf. Discord)
- Just rebase on develop until the CI is green

**Comment by haammar-ledger** [comment]
Replaced with https://github.com/LedgerHQ/ledger-live/pull/3390

**Pull request closed without merging**
