### PR TITLE
feat: use ledger proxy for hedera nodes

### PR DESCRIPTION
**Pull request by Sheng-Long**
### 📝 Description

Use ledger proxy for hedera nodes

### ❓ Context

- **Impacted projects**: `` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by haammar-ledger — COMMENTED** [review]
Thanks!
Can you please just add a changeset? using `pnpm changeset`

**Review by haammar-ledger — COMMENTED** [review]
This seems to break the integration tests, see CI results, not sure how it's related to the changes though.

**Comment by Sheng-Long** [comment]
Integration tests are also failing for the same reason on develop.  Seems to not be an issue with this PR

**Comment by Sheng-Long** [comment]
To reiterate what the issue is here: 

The integration tests cannot pass with the Hedera client being set up for the ledger proxies.   The Hedera SDK will automatically select GRPC nodes when running in node (instead of GRPCWeb).  The proxies still seem to work in-app.

Possible solutions include a mock client for only integration testing that uses the default nodes instead of the proxy nodes or skipping these tests for Hedera

**Comment by Sheng-Long** [comment]
Please do not close this PR

**Comment by haammar-ledger** [comment]
Hi @Sheng-Long, until we decide to do something more advanced, let's disable integration tests for Hedera :pensive: 
Easiest way to do so, I think, is to simply remove `"js"` from [here](https://github.com/LedgerHQ/ledger-live/blob/d4702fb431e06710ae30ec879e52c503861e5b01/libs/ledger-live-common/src/families/hedera/bridge.integration.test.ts#L108).

**Comment by Sheng-Long** [comment]
> Hi @Sheng-Long, until we decide to do something more advanced, let's disable integration tests for Hedera 😔 Easiest way to do so, I think, is to simply remove `"js"` from [here](https://github.com/LedgerHQ/ledger-live/blob/d4702fb431e06710ae30ec879e52c503861e5b01/libs/ledger-live-common/src/families/hedera/bridge.integration.test.ts#L108).

This did not seem to work

**Comment by Sheng-Long** [comment]
Please do not close this PR

**Pull request closed without merging**
