### PR TITLE
LIVE-5809 Drop tron staking

### PR DESCRIPTION
**Pull request by hzheng-ledger**
### 📝 Description

Drop tron staking

### ❓ Context

- **Impacted projects**: LLM, LLD
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5809

### ✅ Checklist

- [x] **Test coverage** 
- [X] **Atomic delivery** 
- [X] **No breaking changes** 

### 📸 Demo
Screenshot 2023-03-29 at 13 21 27

截屏2023-03-29 12 27 50

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by lvndry — APPROVED** [review]

**Review by gre — COMMENTED** [review]
if we drop the feature, why don't we also drop the renderer/families/tron/* modals related to it too?

**Review by hedi-edelbloute — COMMENTED** [review]
Agreed with @gre, modals are dead code, we could actually come back to this PR to get back those modals if we need it again :)
Also you have some conflicts with develop

**Comment by hzheng-ledger** [comment]
@gre @hedi-edelbloute Fixed. Please review again. Thanks a lot

**Review by hedi-edelbloute — APPROVED** [review]
LGTM, thanks huiqi

**Review by gre — APPROVED** [review]

**Comment by gre** [comment]
@hzheng-ledger  FYI this PR fails the tests

**Comment by gre** [comment]
the CI checks that assess for dead code indicate you can delete these files

on LLM

     │ 7 unimported files
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ src/families/tron/IlluVotes.tsx
   2 │ src/families/tron/VoteFlow/01-SelectValidator/Footer.tsx
   3 │ src/families/tron/VoteFlow/01-SelectValidator/index.tsx
   4 │ src/families/tron/VoteFlow/01-SelectValidator/Item.tsx
   5 │ src/icons/Medal.tsx
   6 │ src/icons/Trophy.tsx
   7 │ src/logic/keyboardVisible.ts
   
   on LLD
   
      1 │ src/renderer/families/tron/EarnRewardsInfoModal.tsx

**Comment by hzheng-ledger** [comment]
> the CI checks that assess for dead code indicate you can delete these files
> 
> on LLM
> 
> ```
>    1 │ src/families/tron/IlluVotes.tsx
>    2 │ src/families/tron/VoteFlow/01-SelectValidator/Footer.tsx
>    3 │ src/families/tron/VoteFlow/01-SelectValidator/index.tsx
>    4 │ src/families/tron/VoteFlow/01-SelectValidator/Item.tsx
>    5 │ src/icons/Medal.tsx
>    6 │ src/icons/Trophy.tsx
>    7 │ src/logic/keyboardVisible.ts
>  
> ```
> 
> on LLD
> 
> ```
>       1 │ src/renderer/families/tron/EarnRewardsInfoModal.tsx
> ```
> 
> (it is possible to run locally with `npx unimported` to run on respectively apps/ledger-live-desktop and apps/ledger-live-mobile)

Yes, I see that. Thanks a lot for that. I've removed these files and it seems good now :)

**Pull request merged**
