### PR TITLE
[README] Add GitPOAP Badge to Display Number of Minted GitPOAPs for Contributors

### PR DESCRIPTION
**Pull request by kayla-henrie**
### 📝 Description

Hey all, this PR adds a [GitPOAP Badge](https://docs.gitpoap.io/api#get-v1repoownernamebadge) to the README that displays the number of minted GitPOAPs for this repository by contributors to this repo.

You can see an example of this in [our Documentation repository](https://github.com/gitpoap/gitpoap-docs#gitpoap-docs).

This should help would-be contributors as well as existing contributors find out that they will/have received GitPOAPs for their contributions.

CC: @colfax23 @kayla-henrie

### ❓ Context

- **Impacted projects**: ``N/A
- **Linked resource(s)**: ``N/A

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

Screen Shot 2022-07-13 at 2 39 24 PM

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

I'm not creating a changelog entry for this since the change for GitHub doesn't warrant a new version.

### CODE REVIEW

**Comment by aelmilligy-ledger** [comment]
Hi @kayla-henrie,
Could you add the changesets (you can do so by using the command pnpm changeset)?

**Comment by kayla-henrie** [comment]
Hey @aelmilligy-ledger - We attempted to run the `pnpm changeset`, but it doesn't seem like any of the packages would have changed since as far as we can tell, this is just a change to `README.md`. We attempted to proceed with no packages selected but the tool wouldn't allow us to continue. 

Do you have any thoughts on how we should proceed to create this changeset? 

Thanks for your help!

**Comment by aelmilligy-ledger** [comment]
Hi @kayla-henrie,
In fact, for a readme no need for a changesets. 
Yet, after discussion, unfortunately we'll not consider integrating your GitPOAP badge for now. Nevertheless, we'd like to thank you for your contribution.
Best regards.

**Comment by qd-qd** [comment]
@aelmilligy-ledger I guess you misread the proposal.
There is no needs to support GitPOAP into Ledger Live, in fact, it's the other way around. Today, one GitPOAP exists for this repository, which means someone who contributes to the repository would be able to mint a POAP to prove he is a Ledger Live contributor.
The integration is already up, I took time with the GitPOAP team to set up everything on their side. You can test it by yourself by minting the POAP [here](https://www.gitpoap.io/gh/LedgerHQ/ledger-live) (if one of your PRs have been merged in the past).
The communication around this partnership is planned for September. In any case, I think that adding this badge before the communication can't hurt, that will help external/internal developers to know this is a repository POAP-friendly.

**Pull request merged**
