### PR TITLE
Remove tokens definitions from ICP integration

### PR DESCRIPTION
**Pull request by emmanuelm41**
### 📝 Description

Remove USDC token definition from ICP Integration as it is not a token supported on the network

### ❓ Context

- **Impacted projects**: `crypoassets` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by haammar-ledger — COMMENTED** [review]
Hi @emmanuelm41 please just provide a changeset using `pnpm changeset` and we're good to go :+1: thanks!

**Comment by emmanuelm41** [comment]
> Hi @emmanuelm41 please just provide a changeset using `pnpm changeset` and we're good to go 👍 thanks!

Done! Thanks!

**Review by haammar-ledger — COMMENTED** [review]
Oops I forgot about this, but there are a couple snapshots to update when you change the list of supported currencies/tokens:
- `pnpm desktop test:jest --runTestsByPath src/generate-cryptoassets-md.test.ts -u`
- `pnpm common jest --runTestsByPath src/currencies/sortByMarketcap.test.ts -u`

**Comment by emmanuelm41** [comment]
> Oops I forgot about this, but there are a couple snapshots to update when you change the list of supported currencies/tokens:
> 
> * `pnpm desktop test:jest --runTestsByPath src/generate-cryptoassets-md.test.ts -u`
> * `pnpm common jest --runTestsByPath src/currencies/sortByMarketcap.test.ts -u`

Done!

**Review by haammar-ledger — APPROVED** [review]
@emmanuelm41 we have an ongoing issue with the Desktop tests, that's currently blocking many of our PRs too. Sorry about this :pray: I'll let you know as soon as it's solved on our side, then you'll just have to rebase.

**Comment by emmanuelm41** [comment]
> @emmanuelm41 we have an ongoing issue with the Desktop tests, that's currently blocking many of our PRs too. Sorry about this 🙏 I'll let you know as soon as it's solved on our side, then you'll just have to rebase.

Let me know then!! Thanks for the quick response!

**Comment by haammar-ledger** [comment]
@emmanuelm41 Could you please rebase on `develop`? Let's give this another go.

**Comment by emmanuelm41** [comment]
> @emmanuelm41 Could you please rebase on `develop`? Let's give this another go.

Done!

**Pull request merged**
