### PR TITLE
Fix legacy derivation paths missing for EVM based coins

### PR DESCRIPTION
**Pull request by nyanloutre**
### 📝 Description

Add missing legacy derivation path for every EVM based coins. I use the same address since ledger live is a chrome extension, and until now I had to use metamask on m PC to make transactions for every EVM based coin. This prevent me from aggregating my whole portfolio in ledger live and from using my phone to make transactions on Arbitrum for example.

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Comment by CremaFR** [comment]
Hey ! 
Thanks for the PR ! I'm in the same situation as you are :( 
But I'm afraid there is more work required to make the account selection on OP/Arbitrum/BSC/Polygon to read legacy derivation path, tested your code locally and it doesn't work.
it's a known issue on our side

**Comment by nyanloutre** [comment]
> Hey ! Thanks for the PR ! I'm in the same situation as you are :( But I'm afraid there is more work required to make the account selection on OP/Arbitrum/BSC/Polygon to read legacy derivation path, tested your code locally and it doesn't work. it's a known issue on our side

@CremaFR Hello maybe it's because I didn't affect the concat result ? I just fixed this

**Comment by lambertkevin** [comment]
Thanks for the contribution @nyanloutre ! 
Unfortunately, that's an expected behavior, we only want to scan old derivation paths for currencies we were supporting at the time we had them as default. New currencies are relying on services with rate limits, so the more addresses we check, the long the discovery will be, so we chose to not support them "by default". 

I'll close your PR, but feel free to create a github issue so we can track the demand 👌

**Comment by lambertkevin** [comment]
@CremaFR @nyanloutre Sorry I closed the PR in the middle of your discussion, my bad, didn't refresh the page before posting 😞

**Pull request closed without merging**
