### PR TITLE
LIVE-4429 Force Polkadot Nano app v15.9300.0

### PR DESCRIPTION
**Pull request by haammar-ledger**
### 📝 Description

Set Polkadot minimum Nano app version to latest (15.9300.0)

### ❓ Context

- **Impacted projects**: n/a 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4429 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

- [x] Polkadot integration tests
- [x] Polkadot bot

### CODE REVIEW

**Comment by haammar-ledger** [comment]
:information_source: Integration tests: https://github.com/LedgerHQ/ledger-live/actions/runs/3375787705

**Comment by haammar-ledger** [comment]
:information_source: Bot run: https://github.com/LedgerHQ/ledger-live/actions/runs/3375791015

**Comment by haammar-ledger** [comment]
> information_source Bot run: https://github.com/LedgerHQ/ledger-live/actions/runs/3375891692

At the moment the bot refuses to use the latest app version, need to understand why.

**Comment by haammar-ledger** [comment]
:information_source: New bot run: https://github.com/LedgerHQ/ledger-live/actions/runs/3384141557

**Comment by haammar-ledger** [comment]
Bot and integration tests results are :heavy_check_mark:

**Review by henrily-ledger — APPROVED** [review]

**Pull request merged**
