### PR TITLE
regen screenshots

### PR DESCRIPTION
**Pull request by gre**
### 📝 Description

regen screenshots

### ❓ Context

- **JIRA or GitHub link**: 

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [ ] `npx changeset` was attached.
- [x] **Covered by automatic tests.** 
- [x] **Impact of the changes:** 
  - no change

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Comment by gre** [comment]
flaky tests?

**Comment by nabil-brn** [comment]
> flaky tests?

I think the issue is on the test itself, it takes a screenshot with the app version, this test won't pass whevener the app version change.

**Review by valpinkman — APPROVED** [review]

**Review by nabil-brn — APPROVED** [review]

**Review by cgrellard-ledger — APPROVED** [review]

**Review by mle-gall — APPROVED** [review]

**Review by mcayuelas-ledger — APPROVED** [review]

**Pull request merged**
