### PR TITLE
Feat: fix swap history

### PR DESCRIPTION
**Pull request by sarneijim**
### 📝 Description

Fix swap history.
ERC20 does not appear in the history.

### ❓ Context

- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11285

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Review by kallen-ledger — DISMISSED** [review]
LGTM 👍

**Review by CremaFR — DISMISSED** [review]

**Comment by haammar-ledger** [comment]
@lambertkevin FYI

**Review by lambertkevin — CHANGES_REQUESTED** [review]
That change shouldn't be necessary as we have a logic called `mergeSubAccounts` that is responsible for passing already existing data from a "new instance" of a subAccount to a potentially already existing one.

Maybe the bug is that `swapHistory` is not considered like an array of `Operation` ? 
https://github.com/LedgerHQ/ledger-live/blob/develop/libs/coin-evm/src/logic.ts#L92

**Comment by sarneijim** [comment]
> That change shouldn't be necessary as we have a logic called `mergeSubAccounts` that is responsible for passing new data from a "new instance" of a subAccount to a potentially already existing one (keeping things like operations, pendings & swapHistory).
> 
> Maybe the bug is that `swapHistory` should just be removed from the `updatableSubAccountProperties` ? https://github.com/LedgerHQ/ledger-live/blob/develop/libs/coin-evm/src/logic.ts#L92

Updated

**Review by lambertkevin — APPROVED** [review]
🚀

**Review by kallen-ledger — APPROVED** [review]

**Pull request merged**
