### PR TITLE
Feat(LLD): Enable Tron 2.0 Staking in Ledger Live via Stakekit Live App

### PR DESCRIPTION
**Pull request by Philippoes**
### 📝 Description

This PR introduces Tron staking functionality to Ledger Live users by leveraging deep links to redirect users to the relevant staking flows within the Stakekit Ledger Live app

- The "Stake" button on the Tron account screen now redirects users to the "Earn" screen in the Stakekit Live app, with Tron pre-selected.
- Added deep link support for "Manage Vote" and "Claim Reward" actions, directing users to the corresponding sections within the Stakekit Live app.
- Removed the TronAccountSubHeader component as direct staking functionality is now implemented.

Important: `tron` needs to be added to the `stakePrograms` feature flag

📷 Demo

https://github.com/LedgerHQ/ledger-live/assets/22058587/cc27850a-cd53-4a7c-9f3a-c42ec266e65f

### ❓ Context

[StakeKit](https://www.stakek.it/) aims to simplify Tron 2.0 staking for Ledger Live users with this update. We're integrating staking directly into Ledger Live to make it easier and improve the user experience. This makes managing Tron stakes straightforward, encouraging more users to participate.

JIRA: https://ledgerhq.atlassian.net/browse/LIVE-11441

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.**  please suggest method for testing
- [x] **Impact of the changes:** 
  - This PR impacts the Tron stake button and actionables (Claim Reward, Manage Votes) on the accounts page. 
  - Once tron is included in the `stakePrograms` feature flag it will also be possible to get redirected to Stakekit Live App on `stake` buttons present on the Market screen, Stake drawer, etc

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Review by haammar-ledger — DISMISSED** [review]
Pending CI & QA approval.

**Comment by hedi-edelbloute** [comment]
Hi @Philippoes ! :slightly_smiling_face: 
Looks like there is a small issue spotted by our QA engineers, on LLD builds provided, currently the network pre-selected is an ETH one, can you check if you can reproduce ? :pray:

**Comment by Philippoes** [comment]
Hi @hedi-edelbloute, yes we were able to reproduce it. The AccountIDs passed to our live app were not properly decoded on our end. We resolved the issue on our end and can no longer reproduce the issue. Feel free to resume the QA 😄

**Review by beths-ledger — DISMISSED** [review]

**Review by hedi-edelbloute — APPROVED** [review]

**Review by hedi-edelbloute — APPROVED** [review]

**Pull request merged**
