### PR TITLE
fix(live-common): fix the calculation of spendable balance in Stellar accounts.

### PR DESCRIPTION
**Pull request by overcat**
### 📝 Description

> Buying liabilities equal the total amount of the asset offered to buy aggregated over all offers owned by an account, and selling liabilities equal the total amount of the asset offered to sell aggregated over all offers owned by an account.

https://developers.stellar.org/docs/fundamentals-and-concepts/stellar-data-structures/accounts#trustlines

We need to subtract the selling liabilities from the balance when calculating the spendable balance, instead of the buying liabilities.

### ❓ Context

- **Impacted projects**: `live-common` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7352 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

image

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Comment by overcat** [comment]
Checking why CI failed.

**Review by haammar-ledger — COMMENTED** [review]
Hi @overcat thanks for the fix.

Could you please revert the changes in `libs/ledger-live-common/src/families/stellar/__snapshots__/bridge.integration.test.ts.snap` :pray: they're not needed anymore following https://github.com/LedgerHQ/ledger-live/pull/3452

Also after a second look I'm concerned that the error wasn't spotted in test coverage. Could you please review [the bridge integration tests](https://github.com/overcat/ledger-live/blob/bugfix/stellarspendablebalance/libs/ledger-live-common/src/families/stellar/bridge.integration.test.ts) and update or add a test case, to cover the issue?

**Comment by overcat** [comment]
Hi @haammar-ledger, I added a new file to add testing (just like [account-used.integration.test.ts](https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledger-live-common/src/families/bitcoin/account-used.integration.test.ts)). Is this the best practice? Please let me know if there are any issues.

**Comment by haammar-ledger** [comment]
Hi @overcat close! But it's already the purpose of the bridge integration tests here: https://github.com/overcat/ledger-live/blob/bugfix/stellarspendablebalance/libs/ledger-live-common/src/families/stellar/bridge.integration.test.ts
Also described here in the portal: https://developers.ledger.com/docs/coin/writing-tests/#writing-bridgeintegrationtestts

Could you please update that file? Feel free to add the account data you created here, if you need to.

**Comment by overcat** [comment]
@haammar-ledger PTAL 🙏

**Review by haammar-ledger — APPROVED** [review]
Thanks a lot!

**Pull request merged**
