### PR TITLE
Add TiFi Token Icon

### PR DESCRIPTION
**Pull request by samuel-tifi**
### 📝 Description

Add Logo Icon of TiFi Token.
Website: https://tifi.net/
Contract addresses (BSC): 0x17E65E6b9B166Fb8e7c59432F0db126711246BC0

### ❓ Context

- **Impacted projects**: `` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by Justkant — APPROVED** [review]

**Comment by Justkant** [comment]
@samuel-tifi In order to fix the test you need to edit you're svg as said in the error message
Screenshot 2023-01-24 at 10 34 27

**Comment by samuel-tifi** [comment]
Hi, @Justkant thank you for your comments, may I ask how to run the test so I can verify the fix on my local?

**Comment by samuel-tifi** [comment]
Hi, @Justkant I just pushed a change to fix the test failure, would you take a look for any pending items?

**Review by Justkant — CHANGES_REQUESTED** [review]
Hi, you need to cleanup your branch as you added a lot of code from develop when you updated it

**Comment by samuel-tifi** [comment]
Hi, @Justkant I have opened another PR at https://github.com/LedgerHQ/ledger-live/pull/2416 and closed this one. Would you take a look the new one? Thanks!

**Pull request closed without merging**
