### PR TITLE
feat: add USDC TRC-20 (Tron)

### PR DESCRIPTION
**Pull request by rbarinov**
### 📝 Description

Add USDC TRC-20 Contract to whitelisted token list in ledger-live app

### ❓ Context

- **Impacted projects**: `` ledger-live, ledger-live-mobile

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

No

### 🚀 Expectations to reach

Expect to see USDC TRC-20 token in my ledger-live app, both mobile and desktop

### CODE REVIEW

**Review by haammar-ledger — CHANGES_REQUESTED** [review]
Hi @rbarinov thank you for your contribution.
Can you please:
- Add a changeset using `pnpm changeset`
- Run the following commands to update a couple test snapshots, and include them to this PR:
  - `pnpm common jest --runTestsByPath src/currencies/sortByMarketcap.test.ts -u`
  - `pnpm desktop test:jest --runTestsByPath src/generate-cryptoassets-md.test.js -u`

Thanks.

**Comment by rbarinov** [comment]
> Hi @rbarinov thank you for your contribution.
> Can you please:
> - Add a changeset using `pnpm changeset`
> - Run the following commands to update a couple test snapshots, and include them to this PR:
>   - `pnpm common jest --runTestsByPath src/currencies/sortByMarketcap.test.ts -u`
>   - `pnpm desktop test:jest --runTestsByPath src/generate-cryptoassets-md.test.js -u`
> 
> Thanks.

@haammar-ledger hi, I'm sorry, travelling right now and away from the laptop. İs it blocking to accept the merge request?

**Review by haammar-ledger — APPROVED** [review]

**Comment by aelmilligy-ledger** [comment]
Hi @rbarinov,

Could you have a quick look on the conflicted file and resolve it ? In this case apps/ledger-live-desktop/cryptoassets.md

**Comment by rbarinov** [comment]
> Hi @rbarinov,
> 
> Could you have a quick look on the conflicted file and resolve it ? In this case apps/ledger-live-desktop/cryptoassets.md

@aelmilligy-ledger done, set total number of tokens in apps/ledger-live-desktop/cryptoassets.md equal to 10138 tokens

**Comment by aelmilligy-ledger** [comment]
HI @rbarinov,
Could you do a rebase to resolve the conflict?

**Pull request closed without merging**
