### PR TITLE
[LIVE-10062] Bugfix: Add gasLimit error in Send flows

### PR DESCRIPTION
**Pull request by lambertkevin**
### 📝 Description

This PR improves the basic Send flow of LLM & LLD by displaying the `gasLimit` error (which means the transaction simulation failed and that the transaction will very probably fail at broadcast but people can be stubborn 🤷‍♂️) and forcing users to set manually their `customGasLimit` before continuing.

https://github.com/LedgerHQ/ledger-live/assets/44363395/965e4b5e-1e16-4003-9f8a-c70a0bb4df88

https://github.com/LedgerHQ/ledger-live/assets/44363395/1b59c59a-f17e-45e5-818a-81bee1c400aa

### ❓ Context

- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10062

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [x] `npx changeset` was attached.
- [x] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Review by hedi-edelbloute — APPROVED** [review]
Thanks for the accurate demo

**Comment by gre** [comment]
Capture d’écran 2024-03-07 à 12 08 20

Did this go through product/design team? I am not sure we want this repetition of information. 
(i also know there are ongoing work of improving the errors display on hub side – not exactly on the same area but worth noticing. cc @KVNLS @mle-gall )

**Comment by lambertkevin** [comment]
> Capture d’écran 2024-03-07 à 12 08 20
> 
> Did this go through product/design team? I am not sure we want this repetition of information. (i also know there are ongoing work of improving the errors display on hub side – not exactly on the same area but worth noticing. cc @KVNLS @mle-gall )

This repetition is here just because we're in the "advanced" mode and each input has its own "error" possible to display there. The "big" alert is here now no matter what the mode is. Before we had no error displayed (because `transaction` is never a key of the `errors` object from `getTransactionStauts`, so I don't know what we were tracking before [here](https://github.com/LedgerHQ/ledger-live/pull/6380/files#diff-91b744818c341ff7f90d1dffdd6eece7372c0455b8c64285f254286e5e0c355bL133))
Tbh, I think this is clearly an improvement compared to what it was before, and it can be improved later on by whoever wants to work on the design of this thing.

**Comment by lambertkevin** [comment]
@gre @KVNLS Sorry guys, I'm not going to spend more time on this. If you don't think it fits our quality standards, feel free to close the PR or to commit any change you feel necessary.

**Review by gre — CHANGES_REQUESTED** [review]
(just making this explicit in the pr review that we requested for changes so it no longer appear as pending for review)

**Pull request closed without merging**
