### PR TITLE
typo: manufest -> manifest

### PR DESCRIPTION
**Pull request by sandvige**
### 📝 Description

typo: manufest -> manifest

### ❓ Context

- **Impacted projects**: `iOS`
- **Linked resource(s)**: `N/A` 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

Image from iOS (6)

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by elbywan — APPROVED** [review]
Thanks 😉

**Review by Justkant — APPROVED** [review]

**Comment by elbywan** [comment]
Hey @sandvige could you rebase your PR on develop to make the tests pass?

**Comment by aelmilligy-ledger** [comment]
Hey @sandvige, 
Thank you for your contribution.
Could you add the changesets (use pnpm changeset) to your PR ?
Best regards.

**Comment by aelmilligy-ledger** [comment]
Hey @sandvige ,
Thank you for your contribution.
Regarding the conflict:

With the file **apps/ledger-live-mobile/src/screens/Settings/Developer/CustomManifest.js**, could you merge the develop branch in your branch?

**Pull request merged**
