### PR TITLE
Add Acala and Karura

### PR DESCRIPTION
**Pull request by xlc**
### ❓ Context

- **Impacted projects**: [e.g. `live-desktop`, `@ledgerhq/live-common`]
  
- **Linked resource(s)**:

_Write a clear and concise description of what this pull request is about and why it is needed._

### ✅ Checklist

- [x] **Test coverage**: _Did you write any tests to cover the changes introduced by this pull request?_
- [x] **Atomic delivery**: _Is this pull request standalone? In order words, does it depend on nothing else?_
- [x] **No breaking changes**: _Does this pull request contain breaking changes of any kind? If so, please explain why._

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

----

Migrated from https://github.com/LedgerHQ/ledgerjs/pull/859

### CODE REVIEW

**Comment by elbywan** [comment]
@xlc Can you please fill in the PR template? Otherwise this PR will get closed. Thanks 🙇.

**Comment by xlc** [comment]
Not sure if we need tests for this kind of change.

**Comment by xlc** [comment]
This is still active.

**Review by haammar-ledger — COMMENTED** [review]
Hi @xlc thank you for your contribution and your patience.
Our firmware apps team has informed us that this change is not ready at the moment, your PR will be considered as soon as the Nano app has been fully reviewed.

cc @Jdumas-Ledger @tjulien-ledger

**Comment by gre** [comment]
as the Draft semantic is more "something is to be continued on the work", here it's ready but not mergeable, so i think it's best to be closing for now and then we can reopen the PR when it's ready. cc @haammar-ledger

**Pull request closed without merging**
