### PR TITLE
Upgrade to Electron 21

### PR DESCRIPTION
**Pull request by gre**
### 📝 Description

- **Electron was upgraded from 15 to 21. (major)** as well as "electron-builder"
  - that means we have a new bump of the nodejs version for native module too. So all native library impacted (coins, usb,..)
  - that means we have a new Chromium version. So the UI is impacted. Screenshots have changed due to this.
- Sentry was upgraded (minor)
- playwright was upgraded (minor)

### ❓ Context

- **Impacted projects**: `LLD` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4331 
  - fixes https://github.com/LedgerHQ/ledger-live/issues/1005

### ✅ Checklist

- [x] **Test coverage** covered by playwright tests but non regression on native will be needed for all OSs 
  - [ ] @gre to assess again Sentry still connects correctly
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Comment by gre** [comment]
on it

**Comment by chabroA** [comment]
⚠️  Some things related to `webview` (used in [WebPlatformPlayer](https://github.com/LedgerHQ/ledger-live/blob/ff2d747c1a3aa6bc779d1987c0f2a5e0369c2d72/apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/index.tsx)) don’t work anymore.

In a breaking change in Electron 18 the `nativeWindowOpen` web preference (used [here](https://github.com/LedgerHQ/ledger-live/blob/ff2d747c1a3aa6bc779d1987c0f2a5e0369c2d72/apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/index.tsx#L416)) have [been removed](https://www.electronjs.org/blog/electron-18-0#removed-nativewindowopen) (cf. [this PR](https://github.com/electron/electron/pull/29405))

Now, Ledger live does not seem to receive (and handle) `new-window` events when a live-apps wants to open a new window (regularly used throughout Live Apps to open external contextual info like redirect to Twitter account, open ToS page, etc…).

Havent's found a workaround yet 

This can be tested by opening the Moonpay live app for example and clicking on the Twitter logo or _Contact Us_ links in the bottom left of the app page.

**Comment by chabroA** [comment]
> @chabroA good to know! oh no, that's what we were afraid of back in august. Let's see if we can figure out a solution.

@gre Proposed solution in this PR -> https://github.com/LedgerHQ/ledger-live/pull/1777

**Review by chabroA — APPROVED** [review]

**Review by valpinkman — CHANGES_REQUESTED** [review]
Looks good but a changeset is still missing, it would have been interesting to have infos of the fixes that had to be done to the webviews etc...

**Comment by gre** [comment]
@valpinkman we're going to do this changeset / impact assessment from each team. at the moment we're half complete through it.

**Comment by gre** [comment]
new PR https://github.com/LedgerHQ/ledger-live/pull/2049

**Pull request closed without merging**
