### PR TITLE
[LIVE-3722][LIVE-3744][LIVE-3722] - Bugfix: Fix currencies inferences

### PR DESCRIPTION
**Pull request by lambertkevin**
### 📝 Description

Fixes:
- CLI inferring wrong currency
- Wrong return for default `inferTransactions`
- Missing currencies in the supported list of the CLI
- Reorder cryptoassets/currencies to fix the different side effects (they still need to be addressed !) of having tickers and managerAppName collisions.
- Add polyfillApplication test to make sure Ethereum is found when inferred
- Add a `keywords` key to TOP 30 of marketcap currencies to make the search easier
- Update the implementation of `findCryptoCurrencyByKeyword` to make it smarter and more reliable
- Add tests for all currencies with `findCryptoCurrencyById`, `findCryptoCurrencyByTicker`, `findCryptoCurrencyBy`, `findCryptoCurrencyByScheme`, `findCryptoCurrencyByKeyword`

### ❓ Context

- **Impacted projects**: `cryptoassets`, `live-common`, `cli` 
- **Linked resource(s)**:  
  - https://ledgerhq.atlassian.net/browse/LIVE-3722
  - https://ledgerhq.atlassian.net/browse/LIVE-3744
  - https://ledgerhq.atlassian.net/browse/LIVE-3722

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

Demo is showing an ETH transfer being infered from no `-c` option with its `specific.inferTransactions`, then the same thing working with `-c cronos` with no `specific.inferTransactions`.

https://user-images.githubusercontent.com/44363395/189930546-7483b55d-bacb-410a-9065-ad17d70c501a.mov

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by juan-cortes — CHANGES_REQUESTED** [review]
Seems like the screenshots don't agree with your fix, there's one about adding eth and it shows tether

**Comment by lambertkevin** [comment]
> Seems like the screenshots don't agree with your fix, there's one about adding eth and it shows tether

Correct, I fixed `sortByMarketCap` which was also inferring things on tickers and therefore having issues... :(

**Review by hedi-edelbloute — APPROVED** [review]

**Pull request merged**
