### PR TITLE
Enable `wallet-connect-live-app` for rsk (Rootstock)

### PR DESCRIPTION
**Pull request by ahsan-javaiid**
### ✅ Checklist

- [X] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description
This PR enables `wallet-connect-live-app` for rsk chain. 

### ❓ Context

Related pull request merged in `wallet-connect-live-app`: https://github.com/LedgerHQ/wallet-connect-live-app/pull/194

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Comment by ahsan-javaiid** [comment]
cc: @Justkant for review and considering this PR.

**Review by mcayuelas-ledger — APPROVED** [review]

**Comment by ahsan-javaiid** [comment]
Hi @mcayuelas-ledger @Justkant

Any news on merging and releasing this pull request. Let me know if i can do something to speed up or land this PR in LL.

**Comment by ahsan-javaiid** [comment]
cc: @mcayuelas-ledger @Justkant for review 🙏

**Comment by ahsan-javaiid** [comment]
@KVNLS Need your input on this pull request. Please help to rollout this pull request! 🙏🙏🙏. I will be more than thankful to you if you can help to merge and release this pull request.

**Pull request merged**
