### PR TITLE
feat: swap webview content size listener

### PR DESCRIPTION
**Pull request by adumitrana-ledger**
### ✅ Checklist

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

Adds web view listener for content size, size that will allow the app to set the height and let the web view display entire contents into the swap page.

### ❓ Context

- **JIRA or GitHub link**: 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Review by kallen-ledger — DISMISSED** [review]

**Review by Justkant — COMMENTED** [review]
I'm not sure about this change, is it really necessary ?
Couldn't we update the webview to adapt to the content instead ?

It feels very weird to have an app being able to set the webview size, it's similar to allowing a website to resize my browser, doesn't feel right

Also if you really need this you could do everything in `SwapWebView.tsx` IMO and avoid touching the base `Web3AppWebview`

**Comment by adumitrana-ledger** [comment]
> I'm not sure about this change, is it really necessary ? Couldn't we update the webview to adapt to the content instead ?
> 
> It feels very weird to have an app being able to set the webview size, it's similar to allowing a website to resize my browser, doesn't feel right
> 
> Also if you really need this you could do everything in `SwapWebView.tsx` IMO and avoid touching the base `Web3AppWebview`

Hey, thanks for review 🙏 
I'll link the conversation internally, basically, we need to allow the web view to resize based on the content, to allow swap page scroll on content, rather than only inside the web view.

The quickest way, was to have an observer trigger inside the web app and a listener inside the desktop app, that way every time the content is resized we update the web view with the new size. That's strictly related to Demo1 and will be removed starting with Demo3.

Happy to discuss a better way 🙏

**Review by liviuciulinaru — DISMISSED** [review]

**Review by Justkant — DISMISSED** [review]
LGTM

**Review by Justkant — APPROVED** [review]

**Review by liviuciulinaru — APPROVED** [review]

**Review by kallen-ledger — APPROVED** [review]

**Review by LucasWerey — APPROVED** [review]
For hub files

**Review by mcayuelas-ledger — APPROVED** [review]

**Pull request merged**
