### PR TITLE
chore: add react-navigation flipper devtools

### PR DESCRIPTION
**Pull request by Justkant**
### 📝 Description

Adds developer tools to make debugging easier when using React Navigation.
https://reactnavigation.org/docs/devtools/

While working on https://github.com/LedgerHQ/ledger-live-mobile/pull/2462 I needed to debug the navigation and this helped me a lot

Also updates flipper and cleaned up the flipper performance plugin integration.

### ❓ Context

- **Impacted projects**: `live-mobile` 
- **Linked resource(s)**: `` 
Old pr: https://github.com/LedgerHQ/ledger-live/pull/94

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

 
https://user-images.githubusercontent.com/3009753/184420401-d6789678-36d2-45ee-83c7-3162d8079f1c.mov

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Comment by chabroA** [comment]
Hey, is there a specific config, setup to do to get this working?

I followed the doc in our Readme (cf. [here](https://github.com/LedgerHQ/ledger-live/tree/develop/apps/ledger-live-mobile#flipper-)) to setup Flipper but it looks like Navigation (and performance) plugins are not enabled.

I am using Flipper `0.158.0`.

I built and started the app in debug mode:
```sh
DEBUG_RNDEBUGGER=1 pnpm mobile ios
```

and
```sh
DEBUG_RNDEBUGGER=1 pnpm dev:llm
```

PS: not sure it is necessary to use `DEBUG_RNDEBUGGER` for both commands

Screenshot 2022-08-16 at 14 08 21

**Review by chabroA — COMMENTED** [review]
Hey, is there a specific config, setup to do to get this working?

I followed the doc in our Readme (cf. [here](https://github.com/LedgerHQ/ledger-live/tree/develop/apps/ledger-live-mobile#flipper-)) to setup Flipper but it looks like Navigation (and performance) plugins are not enabled.

I am using Flipper `0.158.0`.

I built and started the app in debug mode:
```sh
DEBUG_RNDEBUGGER=1 pnpm mobile ios
```

and
```sh
DEBUG_RNDEBUGGER=1 pnpm dev:llm
```

PS: not sure it is necessary to use `DEBUG_RNDEBUGGER` for both commands

Screenshot 2022-08-16 at 14 08 21

**Review by chabroA — APPROVED** [review]
Works fine 👍 
N.B: Would need to be properly documented on the wiki (basic Flipper config, needed plugins, etc...)

**Review by elbywan — APPROVED** [review]
Great job, works perfectly out of the box 💯 👍

**Comment by Justkant** [comment]
I'll update the doc and rebase the PR today so that we can merge this

**Review by gre — CHANGES_REQUESTED** [review]
conflicts

**Pull request merged**
