### PR TITLE
Support/add veed icon

### PR DESCRIPTION
**Pull request by taiyangc**
### 📝 Description

Add support for VEED (BEP-20) token icon

Contract address (BNB Chain):  https://bscscan.com/token/0x16fdd1edb14ac4012395a0617a682d81595db486

### ❓ Context

- **Impacted projects**: `@ledgerhq/live-common` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by gre — APPROVED** [review]

**Comment by taiyangc** [comment]
Thanks @gre for the approval. Do I need to do anything about the failing checks or they will auto-resolve eventually?

**Comment by gre** [comment]
cc @haammar-ledger

**Comment by turbovim** [comment]
Merging is blocked. What need we do now? Thanks.

**Comment by LauFuVIM** [comment]
@gre @haammar-ledger - Can you help us with our merge blocked at these 3 failing checks (1) Test Desktop App/Ledger live Desktop tests - failing after 38 seconds,  (2)"Vercel- ledger-live-github-bot - Authorization required to deploy" and (3)  "Codecov/projecthttps://github.com/apps/github-actions   --> "You’re not authorized to merge this pull request."  Much appreciated.

**Pull request closed without merging**
