### PR TITLE
Create GND.svg

### PR DESCRIPTION
**Pull request by New-Grounds-NFT-Game**
Add  Ground Coin token logo.

### 📝 Description

Ground Coin token needs a logo.

### ❓ Context

- **Impacted projects**: `` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Comment by aelmilligy-ledger** [comment]
Hey @New-Grounds-NFT-Game,
Thank you for your contribution. 
Could you add a changeset (by using pnpm changeset) please ?

**Comment by gre** [comment]
```
@ledgerhq/live-common:test:  FAIL  src/__tests__/svg.ts
@ledgerhq/live-common:test:   ● svg icons valid
@ledgerhq/live-common:test: 
@ledgerhq/live-common:test:     no width found in /home/runner/work/ledger-live/ledger-live/libs/ledger-live-common/src/data/icons/svg/GND.svg
```

sanity tests are not passing. Could you try to have the same guidelines as other icons we have in our svg folder? Thanks

**Comment by New-Grounds-NFT-Game** [comment]
I will do this as soon as posible
   
   
   
    El 02/08/2022 17:39 CEST @greweb ***@***.***> escribió:
    
   
     
    
   
     
    
     
   @ledgerhq/live-common:test:  FAIL  src/__tests__/svg.ts

@ledgerhq/live-common:test:   ● svg icons valid

@ledgerhq/live-common:test: 

@ledgerhq/live-common:test:     no width found in /home/runner/work/ledger-live/ledger-live/libs/ledger-live-common/src/data/icons/svg/GND.svg

 
   sanity tests are not passing. Could you try to have the same guidelines as other icons we have in our svg folder? Thanks

**Comment by gre** [comment]
Please reopen a new PR with the fixed logo. Thanks

**Pull request closed without merging**
