### PR TITLE
BACK-4682 - add static crypto assets to dynamic CAL

### PR DESCRIPTION
**Pull request by jnicoulaud-ledger**
### 📝 Description

This pull request splits modules into JSON + ts module for all static assets (cardano, cardano, elrond, solana, stellar, tron), so that the JSON file can be included in the dynamic CAL CDN.

Note: hydrating all those currencies from CAL CDN is **not** implemented in this PR.

### ❓ Context

- **Impacted projects**: ledgerjs, dynamic CAL
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4713, https://ledgerhq.atlassian.net/browse/BACK-4682, #2328

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

We expect new files to be available in CAL CDN:

- <https://cdn.live.ledger.com/cryptoassets/asa.json>
- <https://cdn.live.ledger.com/cryptoassets/cardanoNative.json>
- <https://cdn.live.ledger.com/cryptoassets/esdt.json>
- <https://cdn.live.ledger.com/cryptoassets/spl.json>
- <https://cdn.live.ledger.com/cryptoassets/stellar.json>
- <https://cdn.live.ledger.com/cryptoassets/trc10.json>
- <https://cdn.live.ledger.com/cryptoassets/trc20.json>

### CODE REVIEW

**Comment by lambertkevin** [comment]
Hi @jnicoulaud-ledger ! Thanks for the PR (and sorry for the delay...). Can you try rebasing on develop ? Looks like the CI didn't work this time 😞 
🙏

**Comment by jnicoulaud-ledger** [comment]
Hi @lambertkevin ! I rebased but it seems I hit a Babel bug [here](https://github.com/LedgerHQ/ledger-live/actions/runs/4234289994/jobs/7356372440#step:6:174) related to using tuples with named positional parameters. This Babel bug seems related: babel/babel#13702, but I don't use any JS reserved word as param name so... What do you think ? I can revert to normal tuples.

**Comment by jnicoulaud-ledger** [comment]
@haammar-ledger 

> Do we actually need to version the JSONs in both libs/ledgerjs/packages/cryptoassets/src/data/ and libs/ledgerjs/script/crypto-assets-importer/static/data/?
We don't need it, the idea was to separate inputs from outputs as this is quite confusing. So: inputs in importers, and outputs in ledgerjs/data. And in the next step, importer/static/data will move upstream to CAL.

Propositions:
1. Move static data back directly into ledgerjs
2. Add a "This is a generated file" header to all files generated/copied by importers

> I don't understand the structure in libs/ledgerjs/script/crypto-assets-importer/ with evm and tron being separate from other importers?
I think it's just because the others are single files. Maybe it would be clearer if we move evm,static and tron under importers ?

**Review by haammar-ledger — APPROVED** [review]
@jnicoulaud-ledger Thanks for the answers. From what I understand, this seems acceptable as an intermediate step, but next steps should be planned soon so that we reach our goal of 0 sources of truth in `ledger-live`, not 2 :smile:

**Comment by jnicoulaud-ledger** [comment]
@haammar-ledger We synced with @henrily-ledger and went back to 1 :)

**Pull request merged**
