### PR TITLE
fix(onboarding): update Stax onboarding UI

### PR DESCRIPTION
**Pull request by ak-ledger**
### 📝 Description

Update part of the Stax onboarding UI. This part target the Stax configuration steps.

### ❓ Context

- **Impacted projects**: `LLD` 
- **Linked resource(s)**: [LIVE-10012] 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 📸 Demo

https://github.com/LedgerHQ/ledger-live/assets/146743014/7fbcf2d0-1160-48d2-9592-1983f2da5d85

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

[LIVE-10012]: https://ledgerhq.atlassian.net/browse/LIVE-10012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mcayuelas-ledger — COMMENTED** [review]
LGTM but could you provide a screenshot? :)

**Review by sshmaxime — APPROVED** [review]

**Comment by KVNLS** [comment]
In the video, we see the same wording twice. Can you fix it, please? @ak-ledger 
Screenshot 2023-11-20 at 10 41 37
Screenshot 2023-11-20 at 10 42 04

**Pull request merged**
