### PR TITLE
cardano estimateMaxSpendable fix

### PR DESCRIPTION
**Pull request by pavanvora**
### 📝 Description

This PR fixes the bug for estimateMaxSpendable method in Cardano

### ❓ Context

- **Impacted projects**: `ledger-live-common` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3440 

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo
Screenshot 2022-08-17 at 2 10 37 PM

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by haammar-ledger — APPROVED** [review]

**Comment by haammar-ledger** [comment]
@pavanvora Can you please merge develop in? I want to check if that solves the CI failure on **[Build] Mobile App**.
Thanks!

**Comment by haammar-ledger** [comment]
@pavanvora Issue doesn't seem solved and doesn't happen on develop... I don't see why, but I'm wondering if the new version of the `@stricahq/typhonjs` package could have an issue on mobile?...

Really not sure it's related, but you should try using latest pnpm (7.9.3) if you're using a version below.

**Comment by pavanvora** [comment]
@haammar-ledger Anyways, it seems I didn't merge develop properly I'll update it in sometime :)

**Comment by haammar-ledger** [comment]
@pavanvora You can now update from develop again, it should hopefully be better.

**Pull request merged**
