### PR TITLE
support(ledgerjs-cal): CAL update

### PR DESCRIPTION
**Pull request by adrienlacombe-ledger**
### 📝 Description

CAL update

### ❓ Context

- **Impacted projects**: `` lld and llm
- **Linked resource(s)**: `` crypto-assets repo

### ✅ Checklist

- [x] **Test coverage**
- [x] **Atomic delivery**
- [x] **No breaking changes**

### 📸 Demo

n/a

### 🚀 Expectations to reach

n/a

### CODE REVIEW

**Comment by haammar-ledger** [comment]
On hold because current `release` branch contains unmerged CAL updates, when it's merged this branch will need to be rebased and snapshots re-generated...

**Comment by haammar-ledger** [comment]
@adrienlacombe-ledger Conflict on `libs/ledgerjs/packages/cryptoassets/data/erc20-signatures.js` after merge of previous CAL update from branch `release` :disappointed: 
I think this PR should be created again starting from `develop`, or at least the file should be generated again.

**Review by haammar-ledger — CHANGES_REQUESTED** [review]
@adrienlacombe-ledger Conflict on `libs/ledgerjs/packages/cryptoassets/data/erc20-signatures.js` after merge of previous CAL update from branch `release` :disappointed: 
I think this PR should be created again starting from `develop`, or at least the file should be generated again.

**Comment by adrienlacombe-ledger** [comment]
> @adrienlacombe-ledger Conflict on `libs/ledgerjs/packages/cryptoassets/data/erc20-signatures.js` after merge of previous CAL update from branch `release` disappointed I think this PR should be created again starting from `develop`, or at least the file should be generated again.

https://github.com/LedgerHQ/ledger-live/pull/479

**Pull request closed without merging**
