### PR TITLE
github bot for better automation

### PR DESCRIPTION
**Pull request by valpinkman**
Adds a github bot to handle some automation and actions so they do not appear on the workflow list on each PR
It can also sync between this repo and ledger-live-build for async'd actions.

Updated some actions, removed unused ones, updated some workflows as well.

### CODE REVIEW

**Comment by valpinkman** [comment]
Hello

**Comment by valpinkman** [comment]
Yes

**Comment by valpinkman** [comment]
hello

**Comment by valpinkman** [comment]
test

**Comment by valpinkman** [comment]
Hey

**Comment by valpinkman** [comment]
yo

**Comment by valpinkman** [comment]
YOLO

**Comment by valpinkman** [comment]
Yolo

**Comment by valpinkman** [comment]
yolo

**Comment by gre** [comment]
génial

**Pull request closed without merging**
