### PR TITLE
[CI] - [LLM] Add ssh debugging during workflows

### PR DESCRIPTION
**Pull request by jdabbech-ledger**
### 📝 Description

Add ssh action if detox test fail

### ❓ Context

- **JIRA or GitHub link**: **[LIVE-10183](https://ledgerhq.atlassian.net/browse/LIVE-10183)** 

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - 

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

[LIVE-10135]: https://ledgerhq.atlassian.net/browse/LIVE-10135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIVE-10183]: https://ledgerhq.atlassian.net/browse/LIVE-10183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by KVNLS** [comment]
I think that SSH session might be optional.
We could start a job with a parameter to tell that we want to start a SSH session. Maybe we can create a custom action that we can easily reuse across all workflow.
wdyt?
image

**Comment by jdabbech-ledger** [comment]
> I think that SSH session might be optional. We could start a job with a parameter to tell that we want to start a SSH session. Maybe we can create a custom action that we can easily reuse across all workflow. wdyt? image

I guess this is a good idea, thank you

**Review by gre — APPROVED** [review]

**Comment by valpinkman** [comment]
Interesting what you have here. Did you test to ssh into the machine ?

**Comment by jdabbech-ledger** [comment]
> Interesting what you have here. Did you test to ssh into the machine ?

Only on github one, I test it on ledger runners. It works with the ssh key authentication

**Pull request closed without merging**
