### PR TITLE
fix @ledger/react-native-hid for android tiramisu

### PR DESCRIPTION
**Pull request by nicolas-meilan**
https://github.com/LedgerHQ/ledger-live/issues/7786

### ✅ Checklist

- [x] `npx changeset` was attached.
- [x] **Covered by automatic tests.** Bugfix must bring non-regression
- [x] **Impact of the changes:**  the changes impact only the lib ```@ledger/react-native-hid```

### 📝 Description

Android sdk 34 give the following error when use transporter from the lib @ledger/react-native-hid:
```One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts```.

To fix this bug is needed call ```getReactApplicationContext()``` with the ```Context.RECEIVER_NOT_EXPORTED``` attribute.

implementation that throw the error: https://github.com/nicolas-meilan/RungeCoin/blob/master/src/web3/wallet/wallet.ts#L210

### ❓ Context

- JIRA or GitHub link:  [ **ISSUE 7786**](https://github.com/LedgerHQ/ledger-live/issues/7786)

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Comment by KVNLS** [comment]
Hello @nicolas-meilan, first of all, thank you for your contribution!
Can you resync your fork, please? We had an issue with our CI that we had to fix.
Thank you!

**Review by valpinkman — DISMISSED** [review]
LGMT,

⚠️ needs to be tested by us before merging

closes https://github.com/LedgerHQ/ledger-live/issues/7786

**Comment by jorbuedo** [comment]
Thanks, looks about the same as the fix I had on our fork, which is working in prod. Once this is resolved we'll move back to the official package.

**Review by Justkant — APPROVED** [review]

**Comment by valpinkman** [comment]
Hello @nicolas-meilan, thank again for your continuous sync of your branch. 
Since I do not have an Android Tiramisu to test, it will be @mbertin-ledger that will take over and do the test.

Thanks again for your patience 🙏

**Comment by valpinkman** [comment]
@nicolas-meilan you can stop merging develop into your branch for now. As soon as it's reviewed, we will need one last merge/rebase and you should be good to go

**Comment by Justkant** [comment]
@valpinkman & @mbertin-ledger should we reopen the PR ?

**Pull request closed without merging**
