### PR TITLE
chore: temporarily disable macos tests on LLD CI

### PR DESCRIPTION
**Pull request by gre**
### 📝 Description

due to ongoing instabilities with CI macos instance on running Desktop E2E tests, a quick and temporary solution we consider will be to disable the macos tests until we deeply understand the issue and fix it.
LLD being mostly a web project, 99% of the time, bugs happens on all OSs so the risk is reduced. on top of this, most of our developers work on Mac OS so will have tested the feature there. Nevertheless, we still need this restored, simply `git revert` when the fix is there.

### ❓ Context

- **Impacted projects**: LLD tests 
- **Linked resource(s)**: `LIVE-9602` 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by valpinkman — APPROVED** [review]

**Comment by gre** [comment]
as it seems there is a flawky case of market-page-btc-star-linux.png , i'm retriggering to see

**Comment by gre** [comment]
ok we cancel this idea & will refocus on finding a fix + fix other flaky test issues

**Pull request closed without merging**
