### PR TITLE
fix canStake method

### PR DESCRIPTION
**Pull request by pavanvora**
### 📝 Description

fixed canStake method for Cardano 

### ❓ Context

- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11098

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Review by haammar-ledger — COMMENTED** [review]
@pavanvora Thanks!

Looks like there are some tests to update maybe?
https://github.com/LedgerHQ/ledger-live/actions/runs/7914918454/job/21605660941#step:6:3882

**Comment by pavanvora** [comment]
Yeah actually this function itself needs to be updated also the LLD. I'll update the PR. Thanks👍

**Review by hedi-edelbloute — APPROVED** [review]

**Comment by hedi-edelbloute** [comment]
Hey @pavanvora it looks like the tooltip is right but button isn't disabled like before :
image

**Review by hedi-edelbloute — APPROVED** [review]

**Review by haammar-ledger — COMMENTED** [review]
@pavanvora Just need a changeset please :pray: thanks a lot

**Comment by pavanvora** [comment]
@haammar-ledger Added 👍

**Review by hedi-edelbloute — APPROVED** [review]

**Pull request merged**
