### PR TITLE
bugfix/live 7702 Earn dashboard - update no funds modal title dynamically

### PR DESCRIPTION
**Pull request by beths-ledger**
### 📝 Description

- Conditionally update the title of the "no funds modal" on LLD so that it shows a disjunctive ("or") list of available actions only.
- Upgrade i18next package to the latest version on LLD to enable new format functions.

### ❓ Context

- **Impacted projects**:  `Ledger Live desktop`
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7702?atlOrigin=eyJpIjoiY2UwYzg2YTVlZjNjNDJjNGE2MzZmMzBmMDhlMmRlNTkiLCJwIjoiaiJ9

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

image

image

image

> **NB to reviewers**: Relevant changes to the fix are in the second commit: https://github.com/LedgerHQ/ledger-live/pull/4278/commits/f38c91d516d2ec3613fb052a9e804491b9549474

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by mitchellv-ledger — APPROVED** [review]
LGTM

**Comment by gre** [comment]
unit tests appear to reveal a problem

```
  ● RecipientField › Feature Flag › Flag off › should not change domain

    Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

      153 |   account = ethMockAccount,
      154 | ) => {
    > 155 |   const { t } = useTranslation();
          |                               ^
```

**Comment by sshmaxime** [comment]
Hey guys, i'm having some issue because `react-test-renderer` is not in the same version as `react`. https://github.com/testing-library/react-hooks-testing-library/issues/66 is it okay if I downgrade to `17.0.2` ?

**Pull request merged**
