### PR TITLE
Terms of use update popup

### PR DESCRIPTION
**Pull request by thomasrogerlux**
### ❓ Context

- **Impacted projects**: `live-desktop`
  
- **Linked resource(s)**: [LIVE-1916], https://github.com/LedgerHQ/ledger-live-desktop/pull/4927

We wish to notify users properly when the Terms of Use gets updated, directly through Ledger Live. This PR add a new modal in the main Default component that will open when the isAcceptedTerms returns false and the user isn't in the onboarding. Closing the modal accepts the terms.

### ✅ Checklist

- [x] **Test coverage**: _Did you write any tests to cover the changes introduced by this pull request?_
- [x] **Atomic delivery**: _Is this pull request standalone? In order words, does it depend on nothing else?_
- [ ] **Breaking changes**: _Does this pull request contain breaking changes of any kind? If so, please explain why._

### 📸 Demo

163354474-0468a65f-0f66-4cbc-b575-7d99d9de4849

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

[LIVE-1916]: https://ledgerhq.atlassian.net/browse/LIVE-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ychen-ledger — APPROVED** [review]
Validated on the old PR https://github.com/LedgerHQ/ledger-live-desktop/pull/4927

**Review by LFBarreto — APPROVED** [review]

**Review by valpinkman — APPROVED** [review]

**Review by valpinkman — CHANGES_REQUESTED** [review]
Almost good, it seems the cryptoassets.md needs to be regenerated, and don't forget to add a changelog to your commit ;) 

Other than that, pretty good

**Comment by valpinkman** [comment]
@thomasrogerlux it seems there are new screenshots and the diffs seems to be correct. Can you run a generate-screenshots if you are sure about the diff ?

**Comment by thomasrogerlux** [comment]
> @thomasrogerlux it seems there are new screenshots and the diffs seems to be correct. Can you run a generate-screenshots if you are sure about the diff ?

Oops, this PR isn't supposed to update screenshots. I fixed it and will be removing the "screenshot" tag

**Comment by gre** [comment]
@thomasrogerlux you can rebase or merge in the latest develop and it should pass the CI fully 🤞

**Review by valpinkman — APPROVED** [review]

**Pull request merged**
