### PR TITLE
[SUPPORT] Update cal data

### PR DESCRIPTION
**Pull request by chabroA**
### 📝 Description

Run `import-cal-tokens` under `libs/ledgerjs/package.json` to update CAL data.

Not sure it's necessary since, based on https://github.com/LedgerHQ/ledger-live/pull/4525 it's supposed to be done automatically at each release.

But since the script was broken (cf. https://github.com/LedgerHQ/ledger-live/pull/5195) and I need to update the CAL as part of https://github.com/LedgerHQ/ledger-live/pull/5173 anyways, let's update it in this independent PR in order not to mix everything up.

### 🔗  Related to:
- https://github.com/LedgerHQ/ledger-live/pull/5195
- https://github.com/LedgerHQ/ledger-live/pull/5173

### ❓ Context

- **Impacted projects**: `` 
- **Linked resource(s)**: [] 

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by lvndry — APPROVED** [review]
I think this test in not ran in this PR has no desktop file is impacted but I think you need to update `cryptoassets.md` by running: `pnpm desktop test:jest src/generate-cryptoassets-md.test.ts`

**Review by haammar-ledger — APPROVED** [review]

**Comment by chabroA** [comment]
> I think this test in not ran in this PR has no desktop file is impacted but I think you need to update `cryptoassets.md` by running: `pnpm desktop test:jest src/generate-cryptoassets-md.test.ts`

Good point, tested locally and it seems to already be up to date

**Comment by adrienlacombe-ledger** [comment]
> > I think this test in not ran in this PR has no desktop file is impacted but I think you need to update `cryptoassets.md` by running: `pnpm desktop test:jest src/generate-cryptoassets-md.test.ts`
> 
> Good point, tested locally and it seems to already be up to date

build before

**Comment by chabroA** [comment]
> > > I think this test in not ran in this PR has no desktop file is impacted but I think you need to update `cryptoassets.md` by running: `pnpm desktop test:jest src/generate-cryptoassets-md.test.ts`
> > 
> > 
> > Good point, tested locally and it seems to already be up to date
> 
> build before

Indeed! 🤦‍♂️ 

Side note: looks like there is (still) to many "manual" or "have to know" steps in this process, therefore increasing chances of mistakes or oversight...
- First easy step could be to document this process (even if "it's simple"). The weird thing being that you change stuff under `libs/ledgerjs/` but it has an incidence on an MD file stored under LLD (`apps/ledger-live-desktop/cryptoassets.md`) that is itself generated by running a test 🤯 🤔 
- Second step would be to review this whole weird logic and make it a one step (I do one command and it builds the necessary deps + updates the CAL + the `cryptoassets.md` file)

cc. @haammar-ledger FYI

**Pull request merged**
