### PR TITLE
LIVE-10117: Add license to Ledger Live repo

### PR DESCRIPTION
**Pull request by mohammed-ledger**
### 📝 Description

Add license to Ledger Live repo

### ❓ Context

- **JIRA or GitHub link**: 

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - 

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Comment by gre** [comment]
historically we're on Apache 2 https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledgerjs/LICENSE

**Comment by FabriceDautriat** [comment]
> historically we're on Apache 2 https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledgerjs/LICENSE

Ledger Live desktop was under MIT... hence the same used here.

https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/LICENSE

**Comment by gre** [comment]
@FabriceDautriat wow good finding! so if we have a mixture of licenses, not sure we can set one for the global repo, until we converge it all to one? also the "license" field on package.json files will have to be updated.

**Comment by FabriceDautriat** [comment]
I'll try to figure out the answer to this question @gre 

Please allow me a few days, it's not an urgent matter to be honest.

**Comment by FabriceDautriat** [comment]
@gre here is the final answer

**Context**: Ledger teams created a single repository (monorepo) `LedgerHQ/ledger-live` to group together the code previously contained in several repositories related to Ledger Live.
One subset contains code indicated as being under the [Apache-2.0 license](https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledgerjs/LICENSE), and another one contains code subject to the [MIT license](https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/LICENSE). 
**Problem:** You wonder which license to indicate at the root of the repository and in the metadata of the package.json file, and if there is a need of prior harmonization of the licenses of the different subset (i.e., having only 1 license).

**Answer:** There is no compatibility issue between the 2 licenses (both are “permissive” licenses), so it is absolutely possible to have subsets governed by one or other license. In terms of formalism, **you can indicate literally in the README the license governing each of the subsets and to provide the text of the 2 licenses at the root.**

In the `package.json` file, the `license` field supports [SPDX expressions](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#license), so it is possible to simply specify “MIT AND Apache-2.0" there.

@gre : could you amend this PR to take this into account please ?

**Comment by mohammed-ledger** [comment]
@FabriceDautriat @gre  root license updated :blush:

**Comment by FabriceDautriat** [comment]
OK for me. Thanks a lot. :pray: 

Feel free to merge anytime :+1:

**Review by valpinkman — APPROVED** [review]

**Pull request merged**
