### PR TITLE
Integrate SEI network

### PR DESCRIPTION
**Pull request by hedi-edelbloute**
### 📝 Description

Integrate SEI Network

### ❓ Context

- **Impacted projects**: `LLC` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7906` 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

image

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Comment by haammar-ledger** [comment]
Pending funds to test

**Review by lvndry — APPROVED** [review]

**Comment by lvndry** [comment]
Need to update unit tests

**Review by lvndry — COMMENTED** [review]
Need to update unit tests

**Comment by hedi-edelbloute** [comment]
> Need to update unit tests

Which ones ? Integration is already covered by integration + cosmos framework unit tests

**Comment by lvndry** [comment]
Check out the CI, need to regenerate cryptoassets.md: https://github.com/LedgerHQ/ledger-live/actions/runs/6404391222/job/17384857963

**Comment by lvndry** [comment]
> > Need to update unit tests
> 
> Which ones ? integ tests are WIP and there is already cosmos framework unit tests where I did updates

Check out the CI, need to update cryptoassets.md: https://github.com/LedgerHQ/ledger-live/actions/runs/6404391222/job/17384857963

**Review by Josemoe — COMMENTED** [review]
Hopefully errors are corrected

**Pull request merged**
