### PR TITLE
test: add e2e tests covering more coins + going to first account

### PR DESCRIPTION
**Pull request by gre**
WIP: screenshots will be generated and CI should pass.

### 📝 Description

on LLD an e2e test will open the first added account (first by its appearance in the scanning list, not in the accounts screen)

~~more currencies were also added~~ I couldn't do this, because bunch of coin families actually miss to even provide a `bridge/mock` implementation.

this test is added with the goal to cover more coin cases, because screenshoting the account screen will cover the custom parts of coins.

### ❓ Context

- **Impacted projects**: `LLD tests` 
- **Linked resource(s)**: `n/a` 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by haammar-ledger — APPROVED** [review]
What about LLM?
The coverage is probably pretty different on both already, but wanted to mention just in case you want to do the same there.

**Comment by gre** [comment]
@haammar-ledger  this PR was only focusing on LLD in light of recent regression that was very easy to make because no coverage of these parts, and there are still more to do on just e2e of lld, we're not covering a lot of things today (+ not a lot of coins neither). i don't have experience on LLM to really know what's possible there but indeed someone could help on doing the same on LLM

**Pull request merged**
