### PR TITLE
feat: add axelar token to currencies.ts

### PR DESCRIPTION
**Pull request by Windforcer**
### 📝 Description

Add the Axelar token to currencies.ts file, as part of the Axelar ledger app submission for Ledger Live

### ❓ Context

- **Impacted projects**: `@ledgerhq/cryptoassets`, `live-desktop`
- **Linked resource(s)**: 

### ✅ Checklist

Not sure if test coverage is required

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes**

### CODE REVIEW

**Comment by haammar-ledger** [comment]
Hi @Windforcer  thanks for your contribution.
Can you please add a changeset? See [CONTRIBUTING.md](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#changelogs) for more information.
Thank you.

**Review by haammar-ledger — CHANGES_REQUESTED** [review]
Hi @Windforcer thank you for your contribution.
Can you please:
- Add a changeset using `pnpm changeset`
- Run the following commands to update a couple test snapshots, and include them to this PR:
  - `pnpm common jest --runTestsByPath src/currencies/sortByMarketcap.test.ts -u`
  - `pnpm desktop test:jest --runTestsByPath src/generate-cryptoassets-md.test.js -u`

Please see [CONTRIBUTING.md](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md) for additional information.
Thanks again.

**Comment by Windforcer** [comment]
Understood, I know the Axelar Ledger app submission is still under review. Please let me know once the Nano app review is completed and this PR can be considered. Thanks for you help

**Comment by Windforcer** [comment]
@haammar-ledger Can we re-open this PR? I believe we still want this merged eventually - just at a later time once the Ledger app review is completed. Thanks

**Comment by aelmilligy-ledger** [comment]
Hi @Windforcer,
Thank you for your contribution and for this PR once the ledger app review is completed we'll reopen it.
Best regards.

**Pull request closed without merging**
