### PR TITLE
[Bugfix/LIVE-11823]: hide eth modal post stax onboarding flow

### PR DESCRIPTION
**Pull request by beths-ledger**
### ✅ Checklist

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [x] **Impact of the changes:**  
  - the "Grow Your ETH holdings" modal will no longer display during the post onboarding flow when the user tries the "transfer your assets to Ledger" button. 

### 📝 Description

- add isFromPostOnboardingEntryPoint data param to openModal actions from the post onboarding flow callback
- this adds the param to any modals that might need to use it
- specifically, the "Grow Your ETH holdings" modal will no longer display during the post onboarding flow when the user tries the "transfer your assets to Ledger" button. 

### ❓ Context

- **JIRA or GitHub link**: [LIVE-11823](https://ledgerhq.atlassian.net/browse/LIVE-11823)

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

[LIVE-11823]: https://ledgerhq.atlassian.net/browse/LIVE-11823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by alalmi-ledger — DISMISSED** [review]
approved for QA side, also tested in branch build and confirmed fixed

**Review by lpaquet-ledger — APPROVED** [review]

**Review by liviuciulinaru — APPROVED** [review]

**Review by mcayuelas-ledger — APPROVED** [review]
LGTM

**Review by sshmaxime — APPROVED** [review]

**Review by CremaFR — APPROVED** [review]
LGTM

**Pull request merged**
