### PR TITLE
Generalize the account generator for ethereum to yield more tokens

### PR DESCRIPTION
**Pull request by gre**
### 📝 Description

this changes completely the mock generator and impacts currency that have token accounts, but at same time, it allows to test bigger cases: accounts on ethereum are generated with 100, 60, 20, 0 token accounts.

context: for countervalues, we want account with larger amount of tokens.

### ❓ Context

- **Impacted projects**: `desktop tests, cli` 
- **Linked resource(s)**: `none` 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by valpinkman — APPROVED** [review]
LGTM

For the screenshots, I summon @nabil-brn to make sure we are ok :)

@gre some rebase is needed tho

**Comment by gre** [comment]
for my own sake i'll close this PR. i can't keep maintain this PR every day. 

PR history is here to show the proposal anyway, so if ever qa/hub/coin inté need a richer way to test things in future.
please take it as part of your own backlog if you consider this again , cc @haammar-ledger @LFBarreto

**Pull request closed without merging**
