### PR TITLE
CN-551: Entrypoints for ACRE bitcoin yield

### PR DESCRIPTION
**Pull request by adammino-ledger**
This PR adds the entrypoints to the ACRE liveapp that will allow users to yield bitcoin.

Here the entrypoints that will be covered:
 
https://www.figma.com/design/CaZNBA5WrTVzM8SfXXBxqB/LIVE-APP-%2F-Earn?node-id=16921-83976&node-type=section&t=umykgxjnksoKI9m1-0

### ✅ Checklist

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - When bitcoin is added to the `stakePrograms` list on the feature flags on every entrypoint it should show the label `Yield` instead of `Stake` (icon and position of the button should be the same as Stake)

### 📝 Description

_Replace this text by a clear and concise description of what this pull request is about and why it is needed. Be sure to explain the problem you're addressing and the solution you're proposing._
_For libraries, you can add a code sample of how to use it._
_For bugfixes, you can explain the previous behavior and how it was fixed._
_In case of visual features, please attach screenshots or video recordings to demonstrate the changes._

### ❓ Context

- **JIRA or GitHub link**: 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Review by KVNLS — APPROVED** [review]

**Review by Wozacosta — DISMISSED** [review]
some nitpick otherwise all good 👍

**Comment by Wozacosta** [comment]
Also, you'll need to update some playwright test now that bitcoin accounts have that new `stake` button: 

image

**Review by KVNLS — APPROVED** [review]

**Pull request merged**
