### PR TITLE
[QAA-88] [Playwright] Prevent delegation test flakiness

### PR DESCRIPTION
**Pull request by abdurrahman-ledger**
### ✅ Checklist

- [ ] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 
  - ...

### 📝 Description

_Change test accounts type to mock to use mocked bridge in transactions and prevent flakiness_

### ❓ Context

- **JIRA or GitHub link**: 

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Comment by abdurrahman-ledger** [comment]
generate-screenshots

**Review by ypolishchuk-ledger — DISMISSED** [review]

**Review by KVNLS — APPROVED** [review]

**Review by ofreyssinet-ledger — DISMISSED** [review]
thank you 🙏

**Review by hedi-edelbloute — DISMISSED** [review]

**Review by hedi-edelbloute — APPROVED** [review]

**Review by ofreyssinet-ledger — APPROVED** [review]

**Pull request merged**
