### PR TITLE
YLLD

### PR DESCRIPTION
**Pull request by valpinkman**
### 📝 Description

YLLD -> Yobama Ledger Live Desktop. 
The prophecy is true that one day the great Master of Jedi shall be combined with one of the coolest presidents alive.

### ❓ Context

- **Impacted projects**: `live-desktop` 
- **Linked resource(s)**: `` 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

image

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by elbywan — APPROVED** [review]
Beerproved 🍻 

approved

**Review by bmikh-ledger — APPROVED** [review]

**Comment by memdealer** [comment]
YES WE CAN! 
kudos to the best design 
image

**Comment by alaa-ledger** [comment]
the people deserve Yobama. merge it.

**Review by mnicolas-ledger — APPROVED** [review]
```
                                         .*                                      
                                      .#%(/                                     
                                     ,#%%#(//                                   
                                   */(%%%#((((*                                 
                                 *//((%%%#///###.                               
                                (((/((#%%#////(##(.                             
                              *////(/((###////((###(                            
                            ,////(/(/(((#(//////(((#(,                          
                          .////////((((###///(((((((///,                        
                         *//////////(((###//(((/((((///((,                      
                       #%%&&&#(/((((######//////(((((////#(                     
                     /#(%&%%%(//(#%#####%%(/////((((((//((%#(                   
                   ,//((((#((//(#%%%##%&%%(///(//(((((((((((#(*                 
                 .///////////((#%#%######%(/////(((((((((##(/(/(.               
                ////////////((#%%%########(//////((((((((((((((##(.             
              ////////(((///(##%%%#####((#(///((((((((((((#(///((#%#            
            .(/////((///(/(((##%#%%########/////((/(/(((((#%#(((#%&#%,          
          ./(///(((///(/((##%&%#%%%########/////////((((((##%%%%&&%%#%%,        
         //((((#///////(#(((#######((######////////(/((((#####%&&&%######.      
       *(((/(#(((((((((#(((###%#####(###%%#/////(//(((((((#####%%########%(     
     .//((((((%%#######((###%%%#%%%###%%#%#//((((((((((((###################/   
   .//((((((((((###%%%#%%%%%%%%%%%%#%##%%%%(/(//((((((((((########((((#######%, 
  */(((((((((//(/(((((###%%%&&&&&%%%###%%%%(////(//(((((#(#%#%%%###(((((######%#
*/(/(//((((((///(((((####%%%%%%%%%%%##%%%%#((((((((((((#####%%%%####(((((#####* 
   .//((((((((/((((##%#%%%%%%%#%%%%##%%%%%#(((((((((((#####%%%%%####(((((((     
        ,/(((((((((###########%%%%#%%%%%%##((((((((((######%%%%####((((,        
             ./(((((######%%%%%%%%%%%%%%%##(((((((#(######%%%%####(.            
                  ./#######%%%%%%%%%%%%#####((((((#######%%%%%#,                
                       ,(%#%%%%%%%%%%%#####((((((######%%%%*                    
                            ,#%%%%%%%%#####((((((######(.                       
                                 ,##%%######((((###(                            
                                      .(####((#(.                                                                                                              
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                   . ./&@@@&(* .                                
                                /%/////*****,,,,.(*                             
                             (#/(((((((((,,**/*,****&                           
                          .&####((((#(((((*,***/***/*/(                         
                        .###%%%%##(//((/((/**/*,*,**,**&.                       
                       *&(###%%%##((/*(#(##((/*/***,,,**#%(*.       ....        
       .&&%###%&&@@&#(/(((#%%%%%%#((//**((****/**,,,***/*/****,,***//((((###%.  
      (#*/#%%%%%%#((((((##%%&&&%%##(((((/(((/*(//*/*//***((//(##%#%%##%%%#&%.   
         *@%#&%&%%&&&%%%%%%&&&&&%&@@@@@@@&%##(###&@@@@&&#((%%%#%##%%##@/        
            /&#%&@&&&&@&&&&&&&&&&&&&&@&&#%%%(**/#%%@@&%#%#(#((##((&#.           
               /&%%%%%%%%%&&&&&%&&&&%#((##%%(/*/(((((/(((*(##%@/                
                @%***//##%&&&&%%%%%%###%&%%%(/*/*/#(#((//*(&.                   
            /%*,,,***/(&&&@&&&&&%%%######%%(////**//#(###(,#@/                  
       .#&**********//&@@@@&@&&&&%%#%#%%%%%%#((##((((###*......(                
    .@##/*********/((#%@@@@@@@@&&&%%%%%%&&&#((/(##((#(/****,,,(@                
    *&#%#(/***//((##%%%&@@@@@@@@&&&&&&%%%%%###(((##%#//*****,,,,%.              
    ,@//////((#####%%%%%%&@@@@@@@@&&&&&&&&%#%%#%@@%#((/********,,&,             
   ,%//////((#####%%%%%%##%@@@@@@@@@@&@&&&&&%%@@&%(((//***//(/*,,,*@.           
   .,,,,,,,..........,,,.,,,...,,,..,,,,,,.,,...,,,.,,,,,,,,..,..,..            
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                         .*                                      
                                      .#%(/                                     
                                     ,#%%#(//                                   
                                   */(%%%#((((*                                 
                                 *//((%%%#///###.                               
                                (((/((#%%#////(##(.                             
                              *////(/((###////((###(                            
                            ,////(/(/(((#(//////(((#(,                          
                          .////////((((###///(((((((///,                        
                         *//////////(((###//(((/((((///((,                      
                       #%%&&&#(/((((######//////(((((////#(                     
                     /#(%&%%%(//(#%#####%%(/////((((((//((%#(                   
                   ,//((((#((//(#%%%##%&%%(///(//(((((((((((#(*                 
                 .///////////((#%#%######%(/////(((((((((##(/(/(.               
                ////////////((#%%%########(//////((((((((((((((##(.             
              ////////(((///(##%%%#####((#(///((((((((((((#(///((#%#            
            .(/////((///(/(((##%#%%########/////((/(/(((((#%#(((#%&#%,          
          ./(///(((///(/((##%&%#%%%########/////////((((((##%%%%&&%%#%%,        
         //((((#///////(#(((#######((######////////(/((((#####%&&&%######.      
       *(((/(#(((((((((#(((###%#####(###%%#/////(//(((((((#####%%########%(     
     .//((((((%%#######((###%%%#%%%###%%#%#//((((((((((((###################/   
   .//((((((((((###%%%#%%%%%%%%%%%%#%##%%%%(/(//((((((((((########((((#######%, 
  */(((((((((//(/(((((###%%%&&&&&%%%###%%%%(////(//(((((#(#%#%%%###(((((######%#
*/(/(//((((((///(((((####%%%%%%%%%%%##%%%%#((((((((((((#####%%%%####(((((#####* 
   .//((((((((/((((##%#%%%%%%%#%%%%##%%%%%#(((((((((((#####%%%%%####(((((((     
        ,/(((((((((###########%%%%#%%%%%%##((((((((((######%%%%####((((,        
             ./(((((######%%%%%%%%%%%%%%%##(((((((#(######%%%%####(.            
                  ./#######%%%%%%%%%%%%#####((((((#######%%%%%#,                
                       ,(%#%%%%%%%%%%%#####((((((######%%%%*                    
                            ,#%%%%%%%%#####((((((######(.                       
                                 ,##%%######((((###(                            
                                      .(####((#(.                                                                                                              
```

**Comment by tekiflo** [comment]
pls merge i need to learn from the great master yobama

**Review by malikfassi — APPROVED** [review]
Beautifull

**Comment by bmikh-ledger** [comment]
Hi @valpinkman,

I've been doing some research in terms of the popularity of YOBAMA, and it seems like this PR would drastically assist with the next Obama campaign. We might want to merge it as the US government would pay for any release fees.

Do we have a planned date already? My FBI agent is on the needles.

image

**Comment by alaa-ledger** [comment]
is this a psyop

**Comment by bmikh-ledger** [comment]
image
You won't be closed till it's merged

**Comment by valpinkman** [comment]
> image You won't be closed till it's merged

not closing it don't worry

**Comment by bmikh-ledger** [comment]
image
- Hello yes, do not close the PR, the Actual President is not willing to give up. Desu.

**Comment by MDr164** [comment]
When will this be merged?  This feature is crucial for usability.

**Comment by alaa-ledger** [comment]
screenshot_20230602-132050

**Review by nparigi-ledger — APPROVED** [review]

**Review by mlegall-ledger — APPROVED** [review]

**Pull request merged**
