### PR TITLE
Feat/LIVE-4991 - Desktop: Add discover protect modal on sidebar menu

### PR DESCRIPTION
**Pull request by nparigi-ledger**
### 📝 Description

Desktop: Add discover protect modal on sidebar menu

Also : 
Add protectServicesDiscoverDesktop feature flag
Fix Tag component on react-ui

### ❓ Context

- **Impacted projects**: `` live-desktop, live-common, types-lives, react-ui
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-4991

### ✅ Checklist

- [ ] **Test coverage** 
- [ ] **Atomic delivery** 
- [ ] **No breaking changes** 

### 📸 Demo

image

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by mcayuelas-ledger — APPROVED** [review]

**Comment by gre** [comment]
please rebase on develop. affected files were renamed from jsx to tsx after the merge of https://github.com/LedgerHQ/ledger-live/pull/3066 <- see documentation in this PR on how to migrate. Thanks

**Comment by jules-grenier-ledger** [comment]
Updates were made in https://github.com/LedgerHQ/ledger-live/pull/3139

**Pull request closed without merging**
