### PR TITLE
Support/add more discover tests

### PR DESCRIPTION
**Pull request by ggilchrist-ledger**
### 📝 Description

- Adding more discover tests for the following SDK functions:
  - `listCurrencies`
  - `signTransaction`
- Updating methods and screenshots for new account drawer
- Moved Dummy Live App to `apps/ledger-live-desktop/tests/utils/dummy-live-app`
- Added build steps to github workflows to build the Dummy Live App

### ❓ Context

- **Impacted projects**: N/A
- **Linked resource(s)**: N/A

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

https://user-images.githubusercontent.com/87659842/181780910-4f5d57c7-576d-4cd7-907e-d13e8fece35f.mov

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by nabil-brn — APPROVED** [review]
🚀

**Review by Justkant — APPROVED** [review]
LGTM

**Review by chabroA — CHANGES_REQUESTED** [review]
On my side I had to add the following to `.pnpmfile.cjs` 
```
      addDependencies("postcss-loader", {
        "postcss-flexbugs-fixes": "*",
        "postcss-preset-env": "*",
        "postcss-normalize": "*",
      }),
```

Otherwise, the `dummy-live-app` project can't build because of a missing dep

**Comment by ggilchrist-ledger** [comment]
It's added back in. Can you resolve the requested change @chabroA ? I'm not sure I can do it from my side

**Pull request merged**
