### PR TITLE
Feat/lmarketdiscover

### PR DESCRIPTION
**Pull request by porenes**
### 📝 Description

Adding a Mint card in the LLM Discover Landing (mainly usefull for iOS)

### ❓ Context

- **Impacted projects**: `` LLM Discover
- **Linked resource(s)**: `` External contrib - no ticket

### ✅ Checklist

- [ ] **Test coverage** N/A
- [ X] **Atomic delivery**
- [X ] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

ezgif com-gif-maker

### CODE REVIEW

**Comment by porenes** [comment]
@LFBarreto I have added the changelog and updated the image from the one provided by design team
Translations are also included in the PR

**Comment by LFBarreto** [comment]
@porenes good for the changelog and preview.
the image doesnt seem to be corect though, pretty sure if you try in light mode it will look weird.
the gradient on the side should be a gradient towards alpha (transparency)
also rebase on develop it should probably fix the ci issues

**Comment by porenes** [comment]
The image was provided by design, I am not in charge of it.
@hzheng-ledger I would have loved to be warned before you deleted the branch my PR was targetting, now I'm down to create a new one.
@LFBarreto my PR was targetting release because I want it to be ready to be released on its own

**Comment by vehicles4real** [comment]
I own at least 14 trillion in crypto. It's no biggie 😜

**Pull request closed without merging**
