### PR TITLE
support: adding wDoge token icon

### PR DESCRIPTION
**Pull request by Justkant**
### 📝 Description

Original PR had errors on the CI: Closes https://github.com/LedgerHQ/ledger-live/pull/2068

Adding **WDOGE (Wrapped Dogecoin)** Token Icon. Support for tokens was added already added at [ledger-live-desktop](https://github.com/LedgerHQ/ledger-live/tree/develop/apps/ledger-live-desktop).

**Contract addresses (Ethereum):**
**WDOGE**: 0x8aa9381b2544b48c26f3b850f6e07e2c5161eb3e

### ❓ Context

- **Impacted projects**: `@ledgerhq/live-common` 
- **Linked resource(s)**: 

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Comment by adrienlacombe-ledger** [comment]
@wanidulf fyi

**Review by chabroA — COMMENTED** [review]
I see that the SVG image has been updated on this PR in comparaison to the original one. The `width` and `height` are now set at 360 instead of 24 in the original PR, which seems to change the icon rendering (at least on GitHub preview in the files changed tab)

**Comment by adrienlacombe-ledger** [comment]
> I see that the SVG image has been updated on this PR in comparaison to the original one. The `width` and `height` are now set at 360 instead of 24 in the original PR, which seems to change the icon rendering (at least on GitHub preview in the files changed tab)

you are right, we need 360 but not like that I think :)

**Comment by wanidulf** [comment]
Hi, I see. If you need the SVG with a width and heigth of 360px, here is a gist with that:

https://gist.github.com/wanidulf/29283e8f52dee4c40e47bd85e02d261b

Let me know if there is anything else. Thank you.

**Review by chabroA — APPROVED** [review]

**Pull request merged**
