### PR TITLE
fix(lld/reducers/devices): fix infinite loading in DeviceAction

### PR DESCRIPTION
**Pull request by ofreyssinet-ledger**
### 📝 Description

The typing of `currentDevice` in the store has been changed from `Device | null | undefined` to `Device | undefined` in this PR #3926. After asking @Justkant who worked on that PR it was made to simplify the typing.

`device: undefined` isn't properly handled by device actions (it results in an infinite loading instead of showing "connect and unlock your device") so **it broke some device actions** (for instance when you open the manager page and no device is connected it just shows a loading indicator instead of showing actual instructions about plugging in and unlocking a device).

In order to fix that, the `currentDevice` should either be defined or null. This keeps the typing simple and fixes the issue.

Ideally we'd do a full cleanup on the device actions in order to have only 2 possible states for a device (either it's defined or it's null i.e no device) but for now let's just fix this simple issue as I'm worried to get tangled in the infinite spaghetti.

video of the issue:

https://github.com/LedgerHQ/ledger-live/assets/91890529/4c3cea77-924b-4109-98f5-f2ebd9ccfcad

### ❓ Context

- **Impacted projects**: `lld` 
- **Linked resource(s)**: [LIVE-9413] 

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

https://github.com/LedgerHQ/ledger-live/assets/91890529/0700e194-e55d-41d3-946a-08a1ec701d95

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

[LIVE-9413]: https://ledgerhq.atlassian.net/browse/LIVE-9413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by alexandremgo — APPROVED** [review]
Thx 🔥

**Review by Justkant — APPROVED** [review]
Damn nice catch, sorry for breaking that

**Comment by ofreyssinet-ledger** [comment]
no worries it was just waiting for someone to break it haha

**Comment by ivp5** [comment]
This issue seems to persist at least in the Intel Mac version, even until current-latest 2.69 version.

Clean/Reset previous install -> Disconnect devices -> Open Ledger Live app -> "Get Started" -> (choose one of Nano devices) -> Already have recovery/Connect your <device name> -> Genuine Check screen, click "Check my Nano" -> Hang on "Loading..." screen, instead of detecting no devices and asking to connect a device.

**Pull request merged**
