### PR TITLE
Add macOS universal app support

### PR DESCRIPTION
**Pull request by elbywan**
### 📝 Description

**Configures electron-builder to produce an universal macOS app, and makes LLD and LLM compatible with arm64 versions of node.js.**

As a side effect to make things work the following packages were upgraded:

- bump electron to ^15
- bump electron-builder to ^23

### ❓ Context

- **Impacted projects**: `ledger-live-desktop`
- **Linked resource(s)**: `N/A`

### ✅ Checklist

- [ ] **Test coverage**. 
- [x] **Atomic delivery**. 
- [x] **No breaking changes**. 

### 📸 Demo

````sh
ledger-live on  support/universal-mac-app [$!?] via  v14.19.3 took 3m27s
❯ file ./apps/ledger-live-desktop/dist/mac-universal/Ledger\ Live.app/Contents/MacOS/Ledger\ Live
./apps/ledger-live-desktop/dist/mac-universal/Ledger Live.app/Contents/MacOS/Ledger Live: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
./apps/ledger-live-desktop/dist/mac-universal/Ledger Live.app/Contents/MacOS/Ledger Live (for architecture x86_64):	Mach-O 64-bit executable x86_64
./apps/ledger-live-desktop/dist/mac-universal/Ledger Live.app/Contents/MacOS/Ledger Live (for architecture arm64):	Mach-O 64-bit executable arm64
````

Screenshot 2022-06-03 at 12 45 44

### 🚀 Expectations to reach

CI passes, except for playwright tests.

#### Playwright

⚠️  There are minor differences in the snapshots, I believe that is caused because this PR bumps electron by 2 major versions which changes the underlying web engine.

### CODE REVIEW

**Review by valpinkman — APPROVED** [review]
AW YISS

**Comment by gre** [comment]
❓ I like fact this is atomic but wonder if would it make sense to "factorize" this with esbuild for QA team as both involve heavy test & possible regression? I also am going to focus my effort on setting up Sentry again so we can have auto report in future working again 🤞 .

**Comment by elbywan** [comment]
> I like fact this is atomic but wonder if would it make sense to "factorize" this with esbuild for QA team as both involve heavy test & possible regression?

@gre Yes this makes sense 👍. I'll check with the QA team how they want to handle this.

**Pull request merged**
