### PR TITLE
[SUPPORT] update-bot-staging-explorer-eth

### PR DESCRIPTION
**Pull request by chabroA**
### 📝 Description

Since the `ethereum` family does not exist anymore, replace it's reference in the `update-bot-staging-explorer-eth` job by `evm`

Questions:
Based on the name of the jobs, it seems like we are expecting to test a currency and not a full family.
Does it make sense for [this job](https://github.com/LedgerHQ/ledger-live/blob/develop/.github/workflows/bot-staging-explorer-eth.yml) (as well as for [the bitcoin one](https://github.com/LedgerHQ/ledger-live/blob/develop/.github/workflows/bot-staging-explorer-btc.yml)) to test the whole family or should they rather only test the `ethereum` and `bitcoin` currencies (replacing `BOT_FILTER_FAMILIES: bitcoin` by `BOT_FILTER_CURRENCIES: bitcoin` and `BOT_FILTER_FAMILIES: evm` by `BOT_FILTER_CURRENCIES: ethereum`)?

### ❓ Context

- **Impacted projects**: `` 
- **Linked resource(s)**: https://github.com/LedgerHQ/ledger-live/pull/4285

### ✅ Checklist

- [ ] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by hedi-edelbloute — APPROVED** [review]
Maybe it would be more suited to do a filter on ethereum goerli and maybe etc on currencies, i think it's a bit historical to have BTC and ETH runs in staging

Let's do this for now

**Comment by haammar-ledger** [comment]
@chabroA Yes your analysis is mostly correct.

Bots used for staging explorers are only relevant for Ledger explorers, so :
- EVM should now indeed use `BOT_FILTER_CURRENCIES` instead of `BOT_FILTER_FAMILIES`, however the currencies should be all the ones coming from the legacy `ethereum` family: `ethereum, ethereum_goerli, ethereum_classic, polygon, bnb, avalanche_c_chain` (list to be confirmed).
- Bitcoin should keep using `BOT_FILTER_FAMILIES` though, since there were no changes there and the whole family still relies on Ledger explorers.

**Review by haammar-ledger — CHANGES_REQUESTED** [review]
See comment above

**Comment by hedi-edelbloute** [comment]
> @chabroA Yes your analysis is mostly correct.
> 
> Bots used for staging explorers are only relevant for Ledger explorers, so :
> 
> * EVM should now indeed use `BOT_FILTER_CURRENCIES` instead of `BOT_FILTER_FAMILIES`, however the currencies should be all the ones coming from the legacy `ethereum` family: `ethereum, ethereum_goerli, ethereum_classic, polygon, bnb, avalanche_c_chain` (list to be confirmed).
> * Bitcoin should keep using `BOT_FILTER_FAMILIES` though, since there were no changes there and the whole family still relies on Ledger explorers.

Indeed if we want to be "iso" we'd need to filter on old ethereum family with a currency filter

**Comment by chabroA** [comment]
> @chabroA Yes your analysis is mostly correct.
> 
> Bots used for staging explorers are only relevant for Ledger explorers, so :
> 
> * EVM should now indeed use `BOT_FILTER_CURRENCIES` instead of `BOT_FILTER_FAMILIES`, however the currencies should be all the ones coming from the legacy `ethereum` family: `ethereum, ethereum_goerli, ethereum_classic, polygon, bnb, avalanche_c_chain` (list to be confirmed).
> * Bitcoin should keep using `BOT_FILTER_FAMILIES` though, since there were no changes there and the whole family still relies on Ledger explorers.

Filtered on the list of currencies previously handled by the `ethereum` specs:

https://github.com/LedgerHQ/ledger-live/blob/18b4a47b4878a23695a50096b7770134883b8a2e/libs/ledger-live-common/src/families/ethereum/specs.ts#L284-L291

**Pull request merged**
