### PR TITLE
feat/LIVE-3804 Bump hermes-engine dependency to 0.11.0

### PR DESCRIPTION
**Pull request by juan-cortes**
### 📝 Description

Bumps a library to fix some reported vulnerabilities by dependabot

### ❓ Context

- **Impacted projects**: `ledger-live-mobile` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-3804` 

### ✅ Checklist

- [x] **Test coverage** 
- [ ] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach
In theory no breaking changes should happen, anything breaking should be caught in the non regression phase.

### CODE REVIEW

**Comment by valpinkman** [comment]
Good for me. QA might be needed tho ?

**Review by valpinkman — APPROVED** [review]

**Review by lambertkevin — APPROVED** [review]
👌

**Review by elbywan — APPROVED** [review]

**Review by hedi-edelbloute — APPROVED** [review]

**Review by Justkant — APPROVED** [review]

**Review by chabroA — APPROVED** [review]
🚀

**Review by gre — APPROVED** [review]

**Comment by alalmi-ledger** [comment]
QA OK, checked on LLM iOS and Android

**Pull request merged**
