### PR TITLE
LLD TypeScript rework of {components, modals, screens}

### PR DESCRIPTION
**Pull request by gre**
### 📝 Description

This fixes TypeScript errors for all files under 

- `src/renderer/modals`
- `src/renderer/components`
- `src/renderer/screens`

and effectively activate the typechecker for these files.

### ❓ Context

- **Impacted projects**: LLD
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4264

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Comment by gre** [comment]
one dumb thing on the onboarding due to https://github.com/LedgerHQ/ledger-live/commit/30e28ef8817018f4ff637bf38626c2da8cfd20b9 commit that was rebased earlier, hopefully will regen

**Review by mcayuelas-ledger — APPROVED** [review]

**Comment by gre** [comment]
FYI i did a full code diff pass to check there are no other big logic change that wouldn't be explained and all looks fine. about to merge now!

**Pull request merged**
