### PR TITLE
[bugfix] Update Stacks SDK version to fix static fees

### PR DESCRIPTION
**Pull request by haammar-ledger**
### 📝 Description

Upgrades stacks dependencies and fixes use of deprecated feeEstimation method on stacks sdk.

Previous behaviour used deprecated method call and was fixed by replacing it with currently recommended way.

### ❓ Context

- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10833

### ✅ Checklist

Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.

- [x] `npx changeset` was attached.
- [ ] **Covered by automatic tests.** 
- [ ] **Impact of the changes:** 

---

### 🧐 Checklist for the PR Reviewers

- [ ] **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- [ ] **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- [ ] **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- [ ] **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- [ ] **Any new dependencies** have been justified and documented.
- [ ] **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

### CODE REVIEW

**Comment by gre** [comment]
could you check 
```
pnpm desktop why @noble/secp256k1
```

to see if we have opportunity to update other libs that would use a more updated version and dedup this?

**Comment by haammar-ledger** [comment]
@gre Command seems to fail:
```
$ pnpm desktop why @noble/secp256k1

ERROR  Cannot read properties of undefined (reading 'startsWith')

pnpm: Cannot read properties of undefined (reading 'startsWith')
    at getPkgInfo (/home/haammar/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.9/node_modules/pnpm/dist/pnpm.cjs:115831:20)
    at /home/haammar/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.9/node_modules/pnpm/dist/pnpm.cjs:116031:57
    at Array.forEach (<anonymous>)
    at getTreeHelper (/home/haammar/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.9/node_modules/pnpm/dist/pnpm.cjs:116030:28)
    at getTree (/home/haammar/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.9/node_modules/pnpm/dist/pnpm.cjs:115978:14)
    at /home/haammar/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.9/node_modules/pnpm/dist/pnpm.cjs:116253:34
    at Array.forEach (<anonymous>)
    at dependenciesHierarchyForPackage (/home/haammar/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.9/node_modules/pnpm/dist/pnpm.cjs:116226:33)
    at async /home/haammar/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.9/node_modules/pnpm/dist/pnpm.cjs:116190:11
    at async Promise.all (index 0)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by gre** [comment]
@haammar-ledger do you use prototools? you are way outdated on the pnpm version. I recommend to use prototools so it sync with what is defined by .prototools file

**Review by hedi-edelbloute — APPROVED** [review]

**Comment by haammar-ledger** [comment]
Useless IMO as [the same fix](https://github.com/LedgerHQ/ledger-live/pull/5973) was merged into `release`, which is set to be merged to `main` & `develop` today

**Pull request closed without merging**
