### PR TITLE
LIVE-3985: support(ledgerjs-cal): 20220930 CAL update

### PR DESCRIPTION
**Pull request by adrienlacombe-ledger**
### 📝 Description

CAL update

### ❓ Context

- **Impacted projects**: `` lld & llm
- **Linked resource(s)**: `` crypto-assets repo

### ✅ Checklist

- [x] **Test coverage**
- [x] **Atomic delivery**
- [x] **No breaking changes**

### 📸 Demo

n/a

### 🚀 Expectations to reach

n/a

### CODE REVIEW

**Review by henrily-ledger — APPROVED** [review]

**Review by gre — CHANGES_REQUESTED** [review]
some tests apparently changed and will need regen

**Comment by adrienlacombe-ledger** [comment]
> some tests apparently changed and will need regen

how do I do that @gre ?

**Comment by gre** [comment]
replaced by https://github.com/LedgerHQ/ledger-live/pull/1442 ?

**Comment by adrienlacombe-ledger** [comment]
nope @gre this is just the good old CAL signing, no changes in the scripts like Sara did.

**Comment by adrienlacombe-ledger** [comment]
seems better now @gre

**Comment by henrily-ledger** [comment]
CAL was already updated with this PR I'm closing this one.
https://github.com/LedgerHQ/ledger-live/pulls?q=bep20

**Pull request closed without merging**
