### PR TITLE
feat: hw-trustchain library + trustchain library bootstrap

### PR DESCRIPTION
**Pull request by gre**
### ✅ Checklist

- [ ] `npx changeset` was attached. no need to.
- [x] **Covered by automatic tests.** 
- [x] **Impact of the changes:** 
  - no impact. we just introduce a library.

### 📝 Description

- Create `hw-trustchain` library implementation (original code author: @pollastri-pierre) on the monorepo. 
- This is the client bindings for the Nano app https://github.com/LedgerHQ/app-trustchain.
- ✅ This was tested manually on Electron and React Native that the library is ready for it (that the crypto curves are working there)
- ✅ it also works on the web (had to activate wasm)
- ✅ a basic button was implemented on the Web Tools `/trustchain` :

Capture d’écran 2024-05-17 à 17 21 56

- Bootstrap `trustchain` package that will be the home for the next iteration.

### ❓ Context

- **JIRA or GitHub link**: [LIVE-12538](https://ledgerhq.atlassian.net/browse/LIVE-12538)

big picture https://ledgerhq.atlassian.net/wiki/spaces/WXP/pages/4717314137/2024-05-17+technical+breakdown+of+core+tasks+and+architecture

---

### 🧐 Checklist for the PR Reviewers

- **The code aligns with the requirements** described in the linked JIRA or GitHub issue.
- **The PR description clearly documents the changes** made and explains any technical trade-offs or design decisions.
- **There are no undocumented trade-offs**, technical debt, or maintainability issues.
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and handled.
- **Any new dependencies** have been justified and documented.
- **Performance** considerations have been taken into account. (changes have been profiled or benchmarked if necessary)

[LIVE-12538]: https://ledgerhq.atlassian.net/browse/LIVE-12538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by sprohaszka-ledger — COMMENTED** [review]
It could be great to start organizing those libraries in other sub directory, instead of having everything in `/libs` (*ledgerjs syndrome*) ;)

**Comment by gre** [comment]
@sprohaszka-ledger i quite disagree, i would actually prefer ledgerjs libs to be flatten in the /libs, because then it's easy to just find the library. at the end of the day, a library is global (in the package.json  and so it's confusing for everywhere that `@ledgerhq/hw-transport` is actually under libs/ledgerjs/packages/hw-transport and nost just libs/hw-transport

**Comment by sprohaszka-ledger** [comment]
@gre, I find it hard to navigate and understand what part of the code base are meaningful together.

But I think this is another topic, not related to this PR

**Comment by gre** [comment]
@sprohaszka-ledger i see. actually i see it could make sense to group libs per team ownership. would help on the codeowners too

**Review by cgrellard-ledger — APPROVED** [review]

**Pull request merged**
