### PR TITLE
live 7891 |  live 5357

### PR DESCRIPTION
**Pull request by kallen-ledger**
### 📝 Description

- add `onBeforeTransaction` callback `useSwapTransaction` hook.
- add unit tests for `onBeforeTransaction`
- add translation for a no rates found error on LLM.
- fix translation key for `withdrawalsBlockedError`
- add `usePageState` to LLD (move hook from LLD to common)

### ❓ Context

- **Impacted projects**: `LLD, LLM, LLC` 
- **Linked resource(s)**: 
      `[LIVE-7891](https://ledgerhq.atlassian.net/browse/LIVE-7891)` 
      `[LIVE-5357](https://ledgerhq.atlassian.net/browse/LIVE-5357)`

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo
image

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

[LIVE-7891]: https://ledgerhq.atlassian.net/browse/LIVE-7891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIVE-5357]: https://ledgerhq.atlassian.net/browse/LIVE-5357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mitchellv-ledger — APPROVED** [review]
LGTM

**Review by sarneijim — APPROVED** [review]

**Review by cksanders — APPROVED** [review]
lgtm

**Comment by kallen-ledger** [comment]
> lgtm, but confirm `Smartling Translation` has been completed before merging.

Thanks for the review! As far as I'm aware the translations will be completed once the release branch is created and not on a feature branch. @sarneijim maybe you can confirm or deny? 😄

**Comment by sarneijim** [comment]
> > lgtm, but confirm `Smartling Translation` has been completed before merging.
> 
> Thanks for the review! As far as I'm aware the translations will be completed once the release branch is created and not on a feature branch. @sarneijim maybe you can confirm or deny? 😄

Translations in Ledger-live are dealing by delivery managers. We will inform Charles and he need to care about it in the next release.

**Pull request merged**
