### PR TITLE
Revert part of "LLD Sentry iteration"

### PR DESCRIPTION
**Pull request by gre**
This reverts part of the commit c77394e41c48069f6e8419ec47f48941b5723c3d.

### 📝 Description

CI may reveal a problem on Mac and Linux on some work shipped by #782 

this tries to revert the part that is the least important of that other PR.

### ❓ Context

- **Impacted projects**: `lld` 
- **Linked resource(s)**: `n/a` 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

### CODE REVIEW

**Review by haammar-ledger — APPROVED** [review]
Blind checking, trusting the green CI :slightly_smiling_face:

**Review by elbywan — APPROVED** [review]

**Review by hedi-edelbloute — APPROVED** [review]

**Review by Justkant — APPROVED** [review]

**Comment by Justkant** [comment]
We should probably add a changeset

**Comment by gre** [comment]
@Justkant what would the changeset says? it's reverting something that is not yet in production.

**Comment by Justkant** [comment]
> @Justkant what would the changeset says? it's reverting something that is not yet in production.

My bad, I thought it was already shipped in the hotfix and would just say that it fixes the sentry integration

**Comment by gre** [comment]
/generate-screenshots

flawky?

**Comment by gre** [comment]
reverting to the first commit of this PR, idk what happened with the snapshots 🤯  in any case, that first commit appear to solve the develop problem so we'll merge once it pass again

**Pull request merged**
